src/main/java/dinkplugin/DinkPlugin.java
src/test/java/dink/test.kt

While looking at #8 - I started thinking about gold and trimmed amour, as well as heraldic pieces, and I realized the existing regex does not match them.
While discussing adding `\(.+\)?` to the end of the regex, pajlada noted that we might as well just use `(.*)` and I agree with him.
https://regex101.com/r/OlqXHe/1
Fixes #3

Simplify and add tests for `COLLECTION_LOG_REGEX`

---

src/main/java/dinkplugin/DinkPluginConfig.java

As you might have noticed, but not really cared, each group of notifications has a differing setting order.
`(the first 4 have one standard and the last 3 have another)`
I went ahead and standardized it to the following `(I picked the one the last 3 used)`:
1. Enable
2. Send Image
2a/b. notification_specific_settings 
3. Notification Message
before: (rectangle = bad | circle = good)
after:

Standardize settings order

---

src/main/java/dinkplugin/DinkPlugin.java

Loot from pickpocketing and [EVENT](https://github.com/runelite/runelite/blob/9370b8238fe3fad9ff30d9bc58bdd827af5a35df/runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java#L993-L1048)'s should not trigger a notification if `notifyLoot` is disabled
Addresses https://github.com/MidgetJake/UniversalDiscordNotifier/issues/16

fix: honor notify loot setting for pickpocket and containers

---

src/main/java/dinkplugin/DinkPlugin.java
src/test/java/dinkplugin/MatchersTest.kt

As noted by [the wiki](https://oldschool.runescape.wiki/w/Pet#Obtaining_a_pet): 
> if a player receives a pet while having a follower out (for example, a cat), it will be placed into their inventory.
> When this occurs, the message in the chatbox will instead state `You feel something weird sneaking into your backpack.`
Currently the regex does not match this variation. This PR updates the regex to match and also makes the regex non-capturing since there's nothing that needs to be captured anyway. Also adds some of those cool tests.

Fix `PET_REGEX` not matching when you already have a pet out + add tests

---

build.gradle.kts
gradle.properties

Only apply the kotlin gradle plugin for the test suite.
Now, kotlin does not appear for any relevant non-test configurations: https://gist.github.com/iProdigy/15f39902dda316bfc631ea4558122c20

chore: only apply kotlin plugin to test task types

---

.github/workflows/gradle.yml
.run/Run Dink.run.xml
build.gradle.kts

Require environmental variable `DINK_DEBUG` to be true to reference dependencies not included by runelite

chore: only enable test suite if DINK_DEBUG

---

CHANGELOG.md
src/main/java/dinkplugin/message/DiscordMessageHandler.java

Addresses https://github.com/pajlads/DinkPlugin/pull/50#pullrequestreview-1157583396
Race condition was introduced in https://github.com/pajlads/DinkPlugin/pull/39/commits/c38d14c83f2c0e191236300d900ebc0486fce31f

fix: avoid calling webhook before image captured

---

CHANGELOG.md
gradle.properties
src/test/java/dinkplugin/notifiers/MatchersTest.java

- Made the old kotlin test methods that were migrated to java be in camelCase.
- Fixed the name for a test to properly be "should not trigger".
- Removed unneeded `gradle.properties` file

Make old kotlin test methods camelCase

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPluginConfig.java

I spent way too much time to finally just add a fucking tooltip line.

Add info about requiring the rs setting to be enabled for Collection Log

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPlugin.java
src/main/java/dinkplugin/notifiers/ClueNotifier.java
src/main/java/dinkplugin/notifiers/SlayerNotifier.java

Closes #62
Intuition: clue and slayer notifiers require two event calls to gather all of the data to create the notification. It is possible for only one of these events to be accurately parsed (e.g., transient network issue or too strict regex). As a result, when the next event occurs, it will notify using partially old data. To avoid this, if the notifier is in a partially-parsed state for 2+ ticks, we clear the data (as it does not appear that the complementary event will occur). 
This can be seen as a hotfix while we investigate why the complementary event sometimes is not successfully parsed (or possibly doesn't arrive)
Note: we also simplify the event handling based on the order in which the two events are supposed to be received

fix: prevent old state from appearing in later notifs

---

CHANGELOG.md
README.md
build.gradle.kts
src/main/java/dinkplugin/Utils.java
src/main/java/dinkplugin/notifiers/LevelNotifier.java
src/main/java/dinkplugin/notifiers/SpeedrunNotifier.java
src/main/java/dinkplugin/notifiers/data/SpeedrunNotificationData.java
src/test/java/dinkplugin/MockedTestBase.java
src/test/java/dinkplugin/notifiers/ClueNotifierTest.java
src/test/java/dinkplugin/notifiers/CollectionNotifierTest.java
src/test/java/dinkplugin/notifiers/CombatTaskMatcherTest.java
src/test/java/dinkplugin/notifiers/CombatTaskNotifierTest.java
src/test/java/dinkplugin/notifiers/DeathNotifierItemTest.java
src/test/java/dinkplugin/notifiers/DeathNotifierTest.java
src/test/java/dinkplugin/notifiers/DiaryNotifierTest.java
src/test/java/dinkplugin/notifiers/KillCountNotifierTest.java
src/test/java/dinkplugin/notifiers/LevelNotifierTest.java
src/test/java/dinkplugin/notifiers/LootNotifierTest.java
src/test/java/dinkplugin/notifiers/MockedNotifierTest.java
src/test/java/dinkplugin/notifiers/PetNotifierTest.java
src/test/java/dinkplugin/notifiers/QuestNotifierTest.java
src/test/java/dinkplugin/notifiers/SlayerNotifierTest.java
src/test/java/dinkplugin/notifiers/SpeedrunNotifierTest.java

Utilize mockito to test all notifiers using stub methods & injected mock objects; following up from #73 
In short, we provide realistic inputs (runelite events) to each notifier and check whether the corresponding output (NotificationBody) is appropriate

feat: add mocked notifier tests

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPlugin.java
src/main/java/dinkplugin/notifiers/ClueNotifier.java
src/main/java/dinkplugin/notifiers/LevelNotifier.java
src/main/java/dinkplugin/notifiers/SlayerNotifier.java

Better handle plugin enable/disable: on disable, clear out saved state. on enable, query the latest skill levels for level notifier to function. 
&nbsp;
Resolves edge case before this patch where no level notification would be fired (because `currentLevels` was not initialized) when:
1. Player logs into game with Dink disabled
2. Dink is enabled
3. Player does single action that earns enough xp to trigger level up
&nbsp;
Another resolved edge case:
1. Player disables Dink
2. Player earns levels (or switches to another account with higher levels)
3. Player enables Dink
4. On next experience gain, level up notification would be fired, even if the incremental experience gain was not a full level

fix: initialize current levels if plugin was disabled

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/message/DiscordMessageHandler.java

Workaround for https://i.imgur.com/SMOGZ8J.png 
By default, retries will occur:  2s after initial failure, 4s after next, 8s after next ~~1s after initial failure, 2s after next fail, 4s after next, 8s after next, 16s after next (i.e., over 30s after the initial attempt, cumulatively)... i'm also open to changing the default values governing this~~

feat: retry failed webhook messages

---

CHANGELOG.md
build.gradle.kts

https://github.com/mockito/mockito/releases/tag/v4.10.0

chore: bump mockito version to 4.10.0

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPluginConfig.java

Noticed the sub-par description of `clueMinValue` while testing #98, it took me too long to realize it wasn't talking about minValue for discord embeds.
The `minLootValue` description was better, but I went ahead and updated it anyway.

Better descriptions for `minValue` settings

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPlugin.java
src/main/java/dinkplugin/SettingsValidator.java
src/main/java/dinkplugin/Utils.java
src/main/java/dinkplugin/notifiers/CollectionNotifier.java
src/main/java/dinkplugin/notifiers/CombatTaskNotifier.java

* Collection log notifier requires `COLLECTION_LOG_NOTIFICATION` = 1 or 3
* If `COMBAT_TASK_REPEAT_POPUP` is enabled, warn that combat task will keep sending notifications on each repeated event

chore: add warning logs for bad runescape settings

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPlugin.java
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/Utils.java
src/main/java/dinkplugin/message/DiscordMessageHandler.java

Default write timeout is 10 seconds. This timeout can be breached for users with slow upload speeds trying to write screenshots of high resolution or detailed (e.g., with HD plugin) environments. This PR raises the write timeout for such calls to 30 seconds.

fix: increase timeout when writing screenshots

---

CHANGELOG.md
build.gradle.kts

https://github.com/mockito/mockito/releases/tag/v4.11.0

chore: bump mockito to 4.11.0

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPlugin.java
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/Utils.java
src/main/java/dinkplugin/notifiers/KillCountNotifier.java
src/main/java/dinkplugin/notifiers/SpeedrunNotifier.java
src/main/java/dinkplugin/notifiers/data/BossNotificationData.java
src/main/java/dinkplugin/util/DurationAdapter.java
src/test/java/dinkplugin/notifiers/KillCountNotifierTest.java
src/test/java/dinkplugin/notifiers/MatchersTest.java

* Allow kill count notification on personal best time (even if interval was not met)
* Utilize separate message template for best time notification
* Add latest fight duration to `extra` json data

feat: track best fight duration in kill count notifier

---

CHANGELOG.md
build.gradle.kts

Dink v1.1.3 contains a number of quality-of-life improvements and bug fixes. Most notably, kill count notifications can fire on new personal best times, loot from unsired can now trigger a notification (experimental), and webhook requests can be attempted multiple times with greater timeout (to work around transient network issues).

Release v1.1.3

---

CHANGELOG.md
src/main/java/dinkplugin/SettingsManager.java
src/test/java/dinkplugin/notifiers/ClueNotifierTest.java
src/test/java/dinkplugin/notifiers/CollectionNotifierTest.java
src/test/java/dinkplugin/notifiers/CombatTaskNotifierTest.java
src/test/java/dinkplugin/notifiers/DeathNotifierTest.java
src/test/java/dinkplugin/notifiers/DiaryNotifierTest.java
src/test/java/dinkplugin/notifiers/KillCountNotifierTest.java
src/test/java/dinkplugin/notifiers/LevelNotifierTest.java
src/test/java/dinkplugin/notifiers/LootNotifierTest.java
src/test/java/dinkplugin/notifiers/MockedNotifierTest.java
src/test/java/dinkplugin/notifiers/PetNotifierTest.java
src/test/java/dinkplugin/notifiers/QuestNotifierTest.java
src/test/java/dinkplugin/notifiers/SlayerNotifierTest.java
src/test/java/dinkplugin/notifiers/SpeedrunNotifierTest.java

Allows for more comprehensive testing; events can be published to the plugin class (which will more realistically forward them to each notifier)

chore(tests): add plugin mockito spy

---

CHANGELOG.md
build.gradle.kts

Dink v1.2.0 most notably now utilizes Discord's rich embed format for webhooks (with the ability to revert to the old format), and can be configured to skip notifications for certain player names.

Release v1.2.0

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/domain/PlayerLookupService.java
src/main/java/dinkplugin/message/Author.java
src/main/java/dinkplugin/message/DiscordMessageHandler.java
src/main/java/dinkplugin/message/NotificationBody.java
src/test/java/dinkplugin/notifiers/MockedNotifierTest.java

Makes the author have a url that can be clicked. By default links to the osrs highscores, but other services are available.
Don't know where you want the config to be placed, but my suggestion would be to create separate "Discord" section? Since some configs are only meant for Discord and not for a generic webhook?

Added player url to the Discord embed author.

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/DiaryNotifier.java

Work towards https://github.com/pajlads/DinkPlugin/issues/124#issuecomment-1384333853
* Reduce init ticks from 8 to 4
* Allow diaryCompletionById initialization even if notifier is disabled
* Add logging for some edge cases

chore: reduce diary initialization delay

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/ClueNotifier.java
src/main/java/dinkplugin/notifiers/LootNotifier.java
src/main/java/dinkplugin/util/ItemUtils.java

Resolves an issue where coins could be thought to have 0 value instead of 1gp each (which @Supinic recently experienced when the clue notifier skipped a notification for [these items](https://i.imgur.com/0fzeOVz.png), given a value threshold of 20k)

fix: improve item price lookup for clue and loot

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/DeathNotifier.java

* Send all of the lost item data in extra data rather than the top 3 most valuable stacks
* Simplify code since kept/lost items can share more logic now^

feat: include all lost items in DeathNotificationData

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/notifiers/LootNotifier.java
src/test/java/dinkplugin/notifiers/LootNotifierTest.java

Closes #133
Note: Relevant loot tracker code is [here](https://github.com/runelite/runelite/blob/f036a0605af90643138f56f764ec20badf46325f/runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java#L869-L901)

feat: allow loot notifier to skip clue scrolls

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/DeathNotifier.java

`DeathNotifier#identifyPker` should prioritize alive, non-clan members, non-friends, non-FC, similar level, skulled players
Work towards addressing edge cases referenced in https://github.com/pajlads/DinkPlugin/issues/116#issuecomment-1378050411

fix: improve player killer identification

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/LootNotifier.java

Fixes #146 
We used the theoretically correct method to get the item quantity but it reports erroneous values, so we hardcode 1 instead given the actual loot [table](https://oldschool.runescape.wiki/w/Unsired#Rewards).

fix: assume singular loot quantity from unsired

---

CHANGELOG.md
README.md
src/main/java/dinkplugin/DinkPlugin.java
src/main/java/dinkplugin/notifiers/PetNotifier.java
src/main/java/dinkplugin/notifiers/data/PetNotificationData.java
src/main/java/dinkplugin/util/Utils.java
src/test/java/dinkplugin/notifiers/MatchersTest.java
src/test/java/dinkplugin/notifiers/PetMatcherTest.java
src/test/java/dinkplugin/notifiers/PetNotifierTest.java

Include pet name in extra notification data when parseable from accompanying clan notification message.
Related: #20

feat: parse pet name from clan message

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/ClueNotifier.java
src/main/java/dinkplugin/notifiers/DiaryNotifier.java
src/main/java/dinkplugin/notifiers/KillCountNotifier.java
src/main/java/dinkplugin/notifiers/LevelNotifier.java
src/main/java/dinkplugin/notifiers/PetNotifier.java
src/main/java/dinkplugin/notifiers/SlayerNotifier.java

Since the internal state of notifiers can be modified by multiple threads (e.g., swing thread can trigger `reset` while client thread is the main user of the internal state), this PR makes all usage of saved state in notifiers thread-safe.
*May* be related to #93

fix: improve thread safety of notifiers

---

CHANGELOG.md
README.md
src/main/java/dinkplugin/SettingsManager.java

* `::dinkexport` - all settings excluding webhook urls
* `::dinkexport all` - all settings including webhook urls
* `::dinkexport webhooks` - only export webhook urls
* `::dinkexport sectionName` - only export notifier settings for a specific section (without url). For example: `::dinkexport bagambles`

feat: require argument for config export to include urls

---

CHANGELOG.md
build.gradle.kts

Dink v1.3.0 most notably features a new notifier for Barbarian Assault high gambles, augments the pet notifier to include the pet name, and improves identification of achievement diary completions.

Release v1.3.0

---

runelite-plugin.properties

Follow-up from #150 (the hub webpage seems to use this file rather than class annotation for searching)

chore: update ba tags in plugin properties files

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/LevelNotifier.java
src/test/java/dinkplugin/notifiers/LevelNotifierTest.java

Notify on level up if jumping over a level that would've warranted a notification.
For example: if interval is set to 5 & player jumps from level 4 to 6 in a skill, a notification will now be fired.
Note: notification will include the *latest* skill level (not the potentially outdated level that matches the interval)

fix: notify when jumping over level that fits interval

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/LevelNotifier.java

Prevents malformed messages if `LevelNotifier#reset` was called concurrently with `LevelNotify#attemptNotify` running on a separate thread

refactor: improve thread safety of level notifier

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/notifiers/DeathNotifier.java
src/test/java/dinkplugin/notifiers/DeathNotifierTest.java

Defaults to 0gp to preserve old behavior (all notifs, despite value lost)

feat(death): optionally skip notif if low value lost

---

CHANGELOG.md
gradle/wrapper/gradle-wrapper.properties

Scala patch obviously doesn't apply to us, but can still update: https://docs.gradle.org/8.0.1/release-notes.html

chore: update to gradle 8.0.1

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/KillCountNotifier.java
src/test/java/dinkplugin/notifiers/KillCountNotifierTest.java

Since Grotesque Guardians has a long death animation, kill count message can be sent seconds after the fight duration message was sent. As a result, the webhook message did not acknowledge the personal best time (discovered by @Felanbird). Now, we hold onto fight duration data for up to 10 ticks so that it can be associated with the delayed kill count message (but we don't apply this timer in the converse direction to avoid delayed messages for other bosses if time information was not sent/parseable).

fix(kc): allow ticks between duration and boss name

---

CHANGELOG.md
build.gradle.kts

Dink v1.3.1 fixes a few edge cases (for level and kill count notifiers), augments pet metadata with the acquisition milestone, and allows skipping death notifications if the total value of the lost items is below a configurable threshold.

Release v1.3.1

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/SlayerNotifier.java
src/test/java/dinkplugin/notifiers/SlayerNotifierTest.java

`SLAYER_COMPLETE_REGEX` was missing a `,` for points (which must be removed for parseInt)

fix: fire slayer notification beyond 999 points

---

CHANGELOG.md
gradle/wrapper/gradle-wrapper.properties

https://docs.gradle.org/8.0.2/release-notes.html

chore: bump gradle to v8.0.2

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/SlayerNotifier.java

Improves correctness if reset (via swing ui thread) occurs concurrently to slayer completion (on client thread)

fix(slayer): improve thread safety of current task

---

CHANGELOG.md
build.gradle.kts

This release includes a good amount of small changes and fixes.
Death notifications spam less by ignoring some safe areas such as LMS.
Chat message warnings in case the Dink config and the Runescape settings are compatible have been improved.
A little UX fix, notifier configuration sections are now collapsed by default.
Fixed a bug that caused the slayer notifier to stop firing when the user receiver more than 999 points (the comma in 1,000 tricker our regex).
Fixed an edge case where not all data about pet acquisitions would be captured due to GIM chat messages being slow at firing.
Link to release with full changelog: https://github.com/pajlads/DinkPlugin/releases/tag/v1.3.2

Release v1.3.2

---

CHANGELOG.md
README.md
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/notifiers/LevelNotifier.java
src/main/java/dinkplugin/notifiers/data/LevelNotificationData.java
src/test/java/dinkplugin/notifiers/LevelNotifierTest.java

Closes #202 
This approach is robust to disabling the level up widget via the new game setting
Note: combat level is also subject to the same min level and level interval config settings

feat: include combat level in skill notifications

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/DeathNotifier.java
src/test/java/dinkplugin/notifiers/DeathNotifierTest.java

`Client#getPlayers` is equivalent to creating a list from `Client#getCachedPlayers` (while filtering out nulls). We can directly create a stream from `getCachedPlayers` (like we do for NPCs), so calling `getPlayers` is technically wasteful

perf(death): avoid creating intermediate list

---

CHANGELOG.md
build.gradle.kts

Dink v1.3.3 includes some minor features, bug fixes, and performance improvements. Most notably, death notification metadata now includes the NPC killer and skill notifications include combat level increases. Further, screenshots are now automatically compressed/rescaled as needed to fit within Discord's file upload limits & the plugin can be configured to momentarily hide the chat box (and PMs) while screenshotting to enhance privacy.
You can find the full release notes at https://github.com/pajlads/DinkPlugin/releases/tag/v1.3.3

Release v1.3.3

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/DeathNotifier.java

`NPCManager#getHealth` *can* yield null. Due to inadequate use of `Comparator.nullsFirst`, `DeathNotifier` could throw a NPE when comparing multiple NPCs with similar characteristics that are all interacting with the local player. As a result, no death notification message would be fired. This patch correctly applies the transformation on the NPC to get the health *before* calling `nullsFirst`, so null safety is restored. Thanks to RomeoGiggleToess for submitting the stacktrace.

fix(death): avoid NPE in multi-NPC killer attribution

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/CollectionNotifier.java

Often collection logs are completed via random events where the user is teleported in the same tick as the event. Due to some race condition, the `screenshotHideChat` can fail to reliably hide the chat for the duration of the screenshot. This PR works around this issue by delaying the collection log screenshot by 20ms.

fix(collection): delay for screenshotHideChat reliability

---

CHANGELOG.md
build.gradle.kts

Dink v1.4.0 most notably includes a new notifier to capture player kills while hitsplats are still visible. This version also fixes a bug with death notifications when multiple NPCs without wiki HP data are simultaneously attacking the player.

Release v1.4.0

---

CHANGELOG.md
src/main/java/dinkplugin/message/DiscordMessageHandler.java

In `DiscordMessageHandler#createMessage`, the `thenAcceptAsync` call on the screenshot future is unnecessary because the passed consumer already uses an executor to launch tasks not on the client thread (so we do not need to use the default fork-join pool implied by the async future). This change has no noticeable impact on gameplay, but is useful for our unit tests that have screenshots enabled (it reduces the chance that gradle terminates a unit test before some separate thread has finished executing the webhook POST): https://github.com/pajlads/DinkPlugin/issues/213#issuecomment-1518993162

chore(DiscordMessageHandler): avoid unnecessary thenAcceptAsync

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/DeathNotifier.java
src/main/java/dinkplugin/notifiers/PlayerKillNotifier.java
src/main/java/dinkplugin/util/WorldUtils.java

Our hardcoded region IDs in `WorldUtils` are *after* instanced-region adjustment, but we were using region IDs without instanced adjustment.
Impacted notifiers:
* Death (fixes https://togithub.com/pajlads/DinkPlugin/issues/116#issuecomment-1520813460 )
* Loot (for player loot)
* Player Kill (for `extra` and `pkSkipSafe`)

fix: account for instanced regions for safe check

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/message/DiscordMessageHandler.java
src/main/java/dinkplugin/message/NotificationBody.java
src/main/java/dinkplugin/util/DiscordProfile.java
src/test/java/dinkplugin/notifiers/MockedNotifierTest.java

Includes information about the logged-in Discord user in notification metadata, which can be helpful for webhook consumers that forward to Discord (or involve a Discord community).
```json
{
"discordUser": {
"id": "1234567890",
"name": "Gamer",
"avatarHash": "abcdefabcdefabcdefabcdef"
},
"playerName": "",
"extra": {},
"embeds": []
}
```
This information is acquired via RPC (that is already executed by base RuneLite), and can be disabled via an advanced config option.

feat: include discord user in metadata

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/DeathNotifier.java

When user dies in Inferno or TzHaar Fight Cave, it is a safe death that we treat exceptionally in that it should bypass the 'ignore safe' config setting. This patch ensures `lostItems` is not populated upon these exceptional safe deaths.

fix: avoid populating lost items upon inferno death

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/LevelNotifier.java
src/test/java/dinkplugin/notifiers/LevelNotifierTest.java

If level notifier was disabled (but levelNotifyCombat was enabled), combat level increases could still trigger a notification

fix: avoid combat level notifications with notifier disabled

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/LevelNotifier.java
src/main/java/dinkplugin/notifiers/data/LevelNotificationData.java

(felanbird):
For some unknown reason, I noticed my normal and virtual levelups were both incorrectly firing combatLevelup notifs, while being at `124.xx` - unsure what could have caused the issue, since I jump around versions while testing.
Notifications were received as follows:
Before this PR:
| Skill | Level | Virtual | combatNotif fired | Correct |
| ----------- | ----------- | -- | -- | -- |
| Attack | 105 | ✔️  | ❌ | ✔️ | 
| Ranged | 108 | ✔️ |✔️ | ❌ |
| Prayer | 88 | ❌ | ✔️ | ❌ |
| Hitpoints | 110 | ✔️  | ✔️ | ❌ |
On this PR:
| Skill | Level | Virtual | combatNotif fired | Correct |
| ----------- | ----------- | -- | -- | -- |
| Ranged | 109 | ✔️ | ❌ | ✔️|
| Prayer | 89 | ❌ | ❌ | ✔️ |
| Prayer | 90 | ❌ | ✔️ | ✔️ |
| Magic | 105 | ✔️ | ❌ | ✔️ |

fix: prefer cached levels for combat level calculation

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/LevelNotifier.java
src/test/java/dinkplugin/notifiers/LevelNotifierTest.java
src/test/java/dinkplugin/notifiers/MockedNotifierTest.java

Previously `initLevels` was only called from `onTick`, but `StatChanged` events initialized the map before the tick event, so `initLevels` wasn't called. This wasn't problematic until we added combat level initialization at the end of `initLevels` (so combat level could be initialized with incomplete level data from the initial StatChanged events). This bug came to light after #240, as it became possible to trigger combat level notifications that don't match the specified interval (due to jumping over a number that is a multiple of the interval).
This PR calls `initLevels` upon the initial `StatChanged` events after login.
In addition, we ensure level initialization only occurs on the client thread (since `initLevels` is called on plugin start up, which can be on the swing thread). As a …

fix: ensure LevelNotifier#initLevels is called

---

CHANGELOG.md
README.md
src/main/java/dinkplugin/notifiers/SlayerNotifier.java
src/main/java/dinkplugin/notifiers/data/SlayerNotificationData.java
src/test/java/dinkplugin/notifiers/SlayerNotifierTest.java

Follow-up from https://github.com/pajlads/DinkPlugin/pull/243#pullrequestreview-1440199599
* https://oldschool.runescape.wiki/w/Special:Search?search=Cave%20Kraken

refactor: split slayer task into monster and kc

---

CHANGELOG.md
build.gradle.kts

Dink v1.5.2 augments rich embeds with relevant wiki links and fixes some bugs. In particular, death notifications feature improved kept/lost classification of stackable items, and level notifications are more reliable for combat levels.

Release v1.5.2

---

CHANGELOG.md
src/main/java/dinkplugin/message/templating/Template.java
src/main/java/dinkplugin/notifiers/ClueNotifier.java
src/main/java/dinkplugin/notifiers/CollectionNotifier.java
src/main/java/dinkplugin/notifiers/CombatTaskNotifier.java
src/main/java/dinkplugin/notifiers/DeathNotifier.java
src/main/java/dinkplugin/notifiers/DiaryNotifier.java
src/main/java/dinkplugin/notifiers/GambleNotifier.java
src/main/java/dinkplugin/notifiers/GroupStorageNotifier.java
src/main/java/dinkplugin/notifiers/KillCountNotifier.java
src/main/java/dinkplugin/notifiers/LevelNotifier.java
src/main/java/dinkplugin/notifiers/LootNotifier.java
src/main/java/dinkplugin/notifiers/PetNotifier.java
src/main/java/dinkplugin/notifiers/PlayerKillNotifier.java
src/main/java/dinkplugin/notifiers/QuestNotifier.java
src/main/java/dinkplugin/notifiers/SlayerNotifier.java
src/main/java/dinkplugin/notifiers/SpeedrunNotifier.java
src/test/java/dinkplugin/message/templating/TemplateTest.java

Creates $O(n)$ fast path instead of $O(n \cdot m)$ for `Template#evaluate`

perf: speed up template evaluation

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/notifiers/LevelNotifier.java
src/test/java/dinkplugin/notifiers/LevelNotifierTest.java

Adds a setting to announce all level-ups past a certain point. i.e. if you had an interval of 5, a minimum skill level of 80, and an override of 95, levels 80, 85, 90, 95, 96, 97, 98, 99 would be announced.

feat: level interval override

---

CHANGELOG.md
build.gradle.kts

Attempting to build the plugin with the latest LTS JDK (17) yields the following compiler exception due to the outdated lombok version mandated by plugin hub restrictions:
```
An exception has occurred in the compiler (17). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program, the following diagnostic, and the parameters passed to the Java compiler in your report. Thank you.
java.lang.NullPointerException: Cannot read field "bindingsWhenTrue" because "currentBindings" is null
[stacktrace omitted]
```
Now we use the latest lombok version if JDK 17+ is detected (won't affect plugin hub as they use 11)

fix(build): allow building plugin with jdk17

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/LevelNotifier.java

Optimization: when skill level is <99, don't need to binary search for virtual level by experience
Can convert level initialization from $O(n \cdot log(m))$ to just $O(n)$ in the best case

perf(level): avoid binary search when unnecessary

---

CHANGELOG.md
build.gradle.kts

Small bump for level bugfix & removal of `Skill.OVERALL`

Release v1.5.3

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPlugin.java
src/main/java/dinkplugin/notifiers/GrandExchangeNotifier.java
src/main/java/dinkplugin/util/SerializedOffer.java

On login, if a GE offer is complete & hasn't been seen before (according to base GE plugin), then allow notification to be fired (given min value is met).
Follow-up from https://github.com/pajlads/DinkPlugin/pull/275#issuecomment-1628081612
Known edge case: if trade completes (triggering a notification to be fired) while playing with GE plugin disabled, player logs out without collecting the proceeds of the trade, user enables GE plugin, and the user logs back into game, then a second (duplicate) notification will be fired. we could address this by writing trade statuses to the dinkplugin config namespace, but this may be overkill

feat(ge): notify new completions upon login

---

CHANGELOG.md
build.gradle.kts

Dink v1.6.0 adds a new notifier for Grand Exchange transactions, and allows a level notification to be sent upon reaching max skill experience (200M).

Release v1.6.0

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/PetNotifier.java

Pet notification is still fired without this PR; this PR just allows us to include `Baron` pet name in notification metadata from the collection log or untradeable drop message, for example.
https://oldschool.runescape.wiki/w/Baron
https://oldschool.runescape.wiki/w/Butch
https://oldschool.runescape.wiki/w/Lil%27viathan
https://oldschool.runescape.wiki/w/Wisp

chore(pet): include new DT2 pet names in notification metadata

---

CHANGELOG.md
src/main/java/dinkplugin/SettingsManager.java
src/main/java/dinkplugin/util/ConfigUtil.java

`pkWebhook`, `groupStorageWebhook`, `grandExchangeWebhook` were not being exported upon `::dinkexport webhooks` (yet *would* be included upon `::dinkexport`)
This PR also loads the webhook config key names dynamically now, so this bug shouldn't happen again when new notifiers are added

fix: export webhook overrides for ge, pk, gim bank notifiers

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/LootNotifier.java
src/test/java/dinkplugin/notifiers/LootNotifierTest.java

Closes #282
Related: https://github.com/runelite/runelite/commit/c2dfda9ede854a5d3f8aeabd1facee36d3951568#diff-54526cb6ca5997b52b0c3195802d3299ccab3e74ed63b9e76d08871bdc2cf602R715 & https://discord.com/channels/301497432909414422/419891709883973642/1138628715199332372

fix: allow whisperer loot to trigger notifications

---

CHANGELOG.md
README.md
src/main/java/dinkplugin/DinkPlugin.java
src/main/java/dinkplugin/notifiers/LootNotifier.java
src/main/java/dinkplugin/notifiers/data/LootNotificationData.java
src/main/java/dinkplugin/util/SerializedLoot.java
src/test/java/dinkplugin/notifiers/LootNotifierTest.java

Closes #296 (Related https://github.com/RinZJ/better-discord-loot-logger/issues/22)
This PR relies upon the base loot tracker plugin observing all kills. In a future PR, we will use boss chat messages to override base loot tracker for more accurate kc stats

feat: include kill count for npc loot notifications

---

CHANGELOG.md
README.md
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/SettingsManager.java
src/main/java/dinkplugin/domain/FilterMode.java
src/test/java/dinkplugin/notifiers/MockedNotifierTest.java
src/test/java/dinkplugin/notifiers/PetNotifierTest.java
src/test/java/dinkplugin/notifiers/SpeedrunNotifierTest.java

Closes #305
Uses @Felanbird's suggestion of a single input box and allow/deny toggle in https://github.com/pajlads/DinkPlugin/pull/114#issuecomment-1375997995 to avoid complexity of the initial approach of having a separate box for the allowlist and denylist.
Still, we discourage use of the allow filter mode since users can get confused when a new account does not fire notifications (because they have not added it to the input box).

feat: add allowlist filter mode for rsn advanced config

---

CHANGELOG.md
build.gradle.kts

Dink v1.6.3 augments notification information and plugin configurability, while expanding webhook support to Discord forum channels. Most notably, loot notifications now include the associated NPC kill count, and filters by item name can be applied to determine whether a loot notification should be triggered. In addition, pet notifications now indicate whether the pet was a duplicate, and level notification messages can include the updated total level of the player.

Release v1.6.3

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/PetNotifier.java
src/main/java/dinkplugin/notifiers/data/PetNotificationData.java
src/test/java/dinkplugin/notifiers/PetNotifierTest.java

Follow-up from https://github.com/pajlads/DinkPlugin/pull/303#issuecomment-1712821862
`duplicate` means *currently* already owned
Previously:
* `would have been followed` => duplicate => previouslyOwned is also true
* `being followed` => not duplicate => unclear whether previouslyOwned (because pet could have died)
New scenarios that are handled:
* `being followed` + collection log notification => not duplicate and not previouslyOwned
* `being followed` + no collection log notification (while collection log chat setting is enabled) => not duplicate, but has been previouslyOwned

feat(pet): distinguish lost pets via collection log messages

---

CHANGELOG.md
README.md
src/main/java/dinkplugin/DinkPlugin.java
src/main/java/dinkplugin/notifiers/SpeedrunNotifier.java
src/main/java/dinkplugin/notifiers/data/SpeedrunNotificationData.java
src/test/java/dinkplugin/notifiers/SpeedrunNotifierTest.java

We now rely on the chat message instead of comparing the times
This means we only fire for new personal bests

fix: stop treating Quest speedrun personal best ties as personal bests

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPluginConfig.java

I went with on by default, I told the issue reporter that off by default was correct, but I realized that outside of death, what I would expect to be the most "common" notifiers are all already default on.

fix: make default setting for screenshots consistent across all notifiers

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/LevelNotifier.java

Previously, upon first login, `initTicks` was constantly getting set to `INIT_CLIENT_TICKS` on tick, so level map initialization couldn't occur. Instead, upon gaining xp in a skill, would the level map be populated for that skill (and `initLevels` would be called, so full map initialization would occur a second later). Typically this is fine, unless the very first xp drop is sufficient to gain a level in the skill. This PR restores `currentLevels` initialization on login, to avoid this bug

fix: allow first xp drop to trigger level notification

---

CHANGELOG.md
src/main/java/dinkplugin/message/DiscordMessageHandler.java
src/main/java/dinkplugin/message/NotificationBody.java
src/main/java/dinkplugin/util/Utils.java

Closes #333
Uses SHA-224 as a sufficiently fast (my laptop achieves a throughput of over 2 million hashes per second, according to JMH) hash function (that doesn't require adding a new dependency) with resistance to collision attacks, preimage attacks, and length extension attacks, so that the underlying account identifier is not revealed (just in case other third party applications use this identifier as auth). If SHA-224 is not available (i.e., user has a very exotic JVM), `dinkAccountHash` is not specified.

feat(metadata): include hashed account unique identifier

---

build.gradle.kts

Our lombok version workaround is no longer required due to https://github.com/runelite/plugin-hub/commit/c998876a32f5714cd9a9d247bdb2658e00ae6184

chore: use lombok 1.18.30 despite jdk version

---

CHANGELOG.md
build.gradle.kts

Dink v1.6.4 fixes some bugs and includes new features. 
In particular, dangerous death detection is improved for CG/TOA, and the kill count notifier now reports the correct challenge duration/PB for (Corrupted) Gauntlet.
In terms of notable features, the diary notifier now includes individual task data, the loot notifier item filters now support wildcards, and a new notifier has been added to inform custom webhook handlers upon character login.

Release Dink v1.6.4

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPlugin.java
src/main/java/dinkplugin/SettingsManager.java
src/main/java/dinkplugin/notifiers/KillCountNotifier.java
src/main/java/dinkplugin/notifiers/LevelNotifier.java
src/main/java/dinkplugin/notifiers/PetNotifier.java

Some notifiers delay sending notifications by a few ticks. This PR fixes some edge cases when config changes (or profile changes) occur *while* a notification is queued.
* When RSN filter changes, we clear all notifier state, even if the update is irrelevant for the current player name. This is overkill; we ought to keep notifier state (i.e., fire the queued notification) if not impacted by the change
* If notifier is disabled while a notification is queued, we ought to not fire the notification.
Fixing these (rare) edge cases is as simple as adding an extra `BaseNotifier#isEnabled` check when queued notification delay has expired (i.e., we're about to release the queued notification)

fix: cancel queued notifications if notifier is concurrently disabled

---

CHANGELOG.md
README.md
src/main/java/dinkplugin/notifiers/MetaNotifier.java
src/main/java/dinkplugin/notifiers/data/LoginNotificationData.java
src/test/java/dinkplugin/notifiers/MetaNotifierTest.java

In addition to skill levels, login notifications now include individual skill XP as well - could be useful for integrations that chart xp over time

feat: include skill xp in login notifications

---

CHANGELOG.md
README.md
src/main/java/dinkplugin/notifiers/MetaNotifier.java
src/main/java/dinkplugin/notifiers/data/LoginNotificationData.java
src/main/java/dinkplugin/util/SerializedPet.java
src/test/java/dinkplugin/notifiers/MetaNotifierTest.java
src/test/java/dinkplugin/notifiers/MockedNotifierTest.java

Relies upon base RL chat commands plugin

feat: include owned pets in login notifications

---

CHANGELOG.md
src/main/java/dinkplugin/util/QuestUtils.java
src/test/java/dinkplugin/notifiers/QuestNotifierTest.java

Prefer `Another Cook's Quest` over `Lumbridge Cook... again` (widget text was changed a couple years ago)
https://oldschool.runescape.wiki/w/File:Another_Cook%27s_Quest_reward_scroll.png#filehistory
old quest name is still referenced in official widgets

feat(quest): use historical name for first Recipe for Disaster quest

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/message/DiscordMessageHandler.java
src/main/java/dinkplugin/message/NotificationBody.java
src/main/java/dinkplugin/notifiers/BaseNotifier.java
src/test/java/dinkplugin/notifiers/PetNotifierTest.java

Work towards #356 (adds `seasonalWorld` to notification metadata)

feat: allow notifications on seasonal worlds to be ignored

---

CHANGELOG.md
build.gradle.kts

I'm not going to re-write the description for 1.6.4* I'll just stick this in the PR body
`1.6.5`: fixed Galvek rematch deaths being handled incorrectly, added a few more pieces of information to LOGIN notifications, migrated widget usage to the new API, and first steps for Leagues handling

Release Dink 1.6.5

---

CHANGELOG.md
README.md
src/main/java/dinkplugin/DinkPlugin.java
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/domain/LeagueRelicTier.java
src/main/java/dinkplugin/domain/LeagueTaskDifficulty.java
src/main/java/dinkplugin/message/DiscordMessageHandler.java
src/main/java/dinkplugin/message/NotificationType.java
src/main/java/dinkplugin/notifiers/LeaguesNotifier.java
src/main/java/dinkplugin/notifiers/data/LeaguesAreaNotificationData.java
src/main/java/dinkplugin/notifiers/data/LeaguesRelicNotificationData.java
src/main/java/dinkplugin/notifiers/data/LeaguesTaskNotificationData.java
src/main/java/dinkplugin/util/Utils.java
src/test/java/dinkplugin/notifiers/LeaguesNotifierTest.java
src/test/java/dinkplugin/util/UtilsTest.java

Closes #356
Notifies on:
* Area unlocked
&nbsp;
* Relic unlocked
&nbsp;
* Task completed

feat: add leagues notifier for areas, relics, and tasks

---

CHANGELOG.md
build.gradle.kts

Dink v1.7.0 adds a new notifier for Leagues IV to capture task completions, area unlocks, and relic selections.

Release v1.7.0

---

CHANGELOG.md
build.gradle.kts

Fixes a bug where the reported "remaining tasks until next area is unlocked" was wrong

Release v1.7.1

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPlugin.java
src/main/java/dinkplugin/SettingsManager.java
src/main/java/dinkplugin/notifiers/CollectionNotifier.java
src/main/java/dinkplugin/notifiers/DiaryNotifier.java
src/main/java/dinkplugin/notifiers/MetaNotifier.java
src/test/java/dinkplugin/notifiers/MetaNotifierTest.java

When client goes into `LOADING` state, we would clear the completed diary state. As a result, if a diary completion occurred shortly after a teleport, the notifier would think there were 0 previous diaries completed. This PR avoids clearing diary state on teleports (and other potentially-small movements that trigger the loading state).

fix: avoid undercounting completed diaries after teleports

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/CollectionNotifier.java
src/test/java/dinkplugin/notifiers/CollectionNotifierTest.java

This ensures completed collection count is updated when character summary tab is selected, even when a collection log notification had already occurred during the session

fix: avoid incrementing completed collections if not initialized

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPlugin.java
src/main/java/dinkplugin/notifiers/LevelNotifier.java
src/test/java/dinkplugin/notifiers/LevelNotifierTest.java

Performs currentLevels initialization on the tick after the first `StatChanged` (or 15 seconds after login if `StatChanged` doesn't occur). 
Previously there could be an edge case where jagex sends character levels on the second game tick (t=1200ms), but we would've initialized at 50 client ticks (t=1000ms), so it would've looked like many level-ups occurred at once
This approach is robust to initial `StatChanged` events being sent on any game tick within the first 15 seconds after login

fix: avoid level initialization before first StatChanged event

---

CHANGELOG.md
src/main/java/dinkplugin/domain/ExceptionalDeath.java
src/main/java/dinkplugin/util/WorldUtils.java

Relies on https://oldschool.runescape.wiki/w/RuneScape:Varplayer/2926 to check whether the player is inside the Jad challenge room since the region is the same
I have tested this in-game and it works as expected.
I have not changed any defaults on purpose, as I think deaths in this challenge may be a bit too frequent to warrant death notifications by default.
Changelog entry change is up for debate, as is naming

Separate Jad challenges from Inferno

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPlugin.java
src/main/java/dinkplugin/domain/ExceptionalDeath.java
src/main/java/dinkplugin/notifiers/DeathNotifier.java
src/main/java/dinkplugin/util/WorldUtils.java

TOB death is only dangerous if hardcore ironman or the full party wipes. We now correctly consider TOB deaths to be safe or dangerous (and the notifier can be configured to dink on safe tob deaths as well). Also: all entry mode tob deaths are safe (so the `Your party has failed.` hud text never appears, as expected)
Follow-up to #363

feat: add tob as exceptional safe death that can trigger a notification

---

CHANGELOG.md
build.gradle.kts

Dink v1.8.0 adds a new notifier to capture player trades, fixes some bugs, and allows customization of which safe deaths should trigger notifications.

Release v1.8.0

---

src/main/java/dinkplugin/message/DiscordMessageHandler.java
src/main/java/dinkplugin/util/Utils.java

Added in https://github.com/runelite/runelite/commit/e5de4d49f534ecfab1976bfe42b170a9f7fb439f (was not initially present when we migrated to new widget api)

refactor: use new runelite method for widget id packing

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/GroupStorageNotifier.java
src/main/java/dinkplugin/util/ItemUtils.java
src/test/java/dinkplugin/UtilsTest.java
src/test/java/dinkplugin/notifiers/GroupStorageNotifierTest.java

Avoids plugin failing to compile if jagex ever changes these item ids

refactor: avoid hardcoding coin item ids

---

CHANGELOG.md
src/main/java/dinkplugin/SettingsManager.java
src/main/java/dinkplugin/util/ConfigUtil.java

fix: import death safe exceptions

---

.github/workflows/gradle.yml
.github/workflows/gradle7.yml

bump to v3 and use their new alias because the old one probably won't get updates anymore

chore(deps): version bump and rename `gradle/gradle-build-action`

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPlugin.java
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/SettingsManager.java
src/test/java/dinkplugin/notifiers/LeaguesNotifierTest.java

Retains the logic in the notifier class for easier reuse next leagues

chore: disable leagues notifier

---

CHANGELOG.md
build.gradle.kts

version bumping now b/c without Scurries being handled, the pet notifs can incorrectly report dupe for the first instance of the pet.
Fixed an issue with `::dinkimport`-ing safe deaths, handle Scurries for pet notifs and disable the Leagues notifier.

Release v1.8.3

---

CHANGELOG.md
build.gradle.kts

Handles the Graveyard Room in MTA as a safe death, allows the user to add death ignores based on regionID & adds a command for getting said regionID's, and changes how the minValue setting works in Loot notifications for PvP Loot Chests

Release v1.8.4

---

CHANGELOG.md
README.md
src/main/java/dinkplugin/SettingsManager.java

Add `::dinkhash` command - can be useful for folks creating custom webhook handlers that want to allowlist certain accounts

feat: add chat command to obtain dink player hash

---

runelite-plugin.properties

changes `Discord-compatible` to `Discord compatible` for the plugin description used by the plugin hub [webpage](https://runelite.net/plugin-hub/) since the dash hinders searchability (i.e., searching `discord` will include dink but `discord ` does not) - this problem doesn't exist for the client-integrated search

chore: update plugin description for website

---

CHANGELOG.md
src/main/java/dinkplugin/SettingsManager.java

Introduced in #429
Discovered by @Felanbird upon switching to a fresh profile & launching our shadow jar
```
net.runelite.client.plugins.PluginInstantiationException: java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "webhookUrl" is null
at net.runelite.client.plugins.PluginManager.startPlugin(PluginManager.java:460)
at net.runelite.client.plugins.PluginManager.lambda$startPlugins$2(PluginManager.java:241)
at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:308)
at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:399) …
```

fix: avoid NPE if webhook url hasn't been configured

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/notifiers/LootNotifier.java
src/test/java/dinkplugin/notifiers/LootNotifierTest.java

fix: exclude deny listed loot from rarity override

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/data/CollectionNotificationData.java

This is the lazy way to better align the fields in collection notifications
There's still a little bit of an alignment jump, but it doesn't feel anywhere near as noticeable this way
<details>
<summary>before/after</summary>
</details>
also we could do this

fix: rename completed entries in collection notifications

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/KillCountNotifier.java
src/test/java/dinkplugin/notifiers/KillCountNotifierTest.java

Also populates `KillCountService` in case base chat commands plugin is not enabled

fix: check lunar chest count for kc notifications

---

CHANGELOG.md
src/main/java/dinkplugin/SettingsManager.java

feat: prevent runelite from resetting empty value for certain config items

---

CHANGELOG.md
build.gradle.kts

Dink v1.10.0 most notably adds a new notifier for chat messages that match user-specified patterns.
Also, the loot notifier now ignores the rarity of denylisted items for the rarity override setting.
In terms of Varlamore, the loot notifier has updated drop rate data, the pet notifier better supports Smol heredit, and the kill count notifier now tracks Lunar Chest openings.
https://github.com/pajlads/DinkPlugin/compare/v1.9.1...62ef660f2f881cc2b76cfde6270b1e64ce94488a

Release v1.10.0

---

CHANGELOG.md
src/main/java/dinkplugin/SettingsManager.java

Reported by @notheowner 
On runelite `ConfigManager#unsetConfiguration`, `ConfigChanged` is fired with null `newValue`  (rather than the default value that is the actual new config value) https://github.com/runelite/runelite/blob/ac52b2b01dc6df3414b8bad2d44884ea2dff29e0/runelite-client/src/main/java/net/runelite/client/config/ConfigManager.java#L940

fix: avoid NPE when single config item is reset

---

src/main/java/dinkplugin/util/ItemUtils.java
src/test/java/dinkplugin/UtilsTest.java
src/test/java/dinkplugin/notifiers/CollectionNotifierTest.java
src/test/java/dinkplugin/notifiers/LootNotifierTest.java

None of our notifiers actually use `ItemStack#getLocation`, but `ItemUtils` previously did because an alternative constructor didn't exist yet
https://github.com/runelite/runelite/commit/b0907b96bf7e47375611fbd8b0aff4f3577c6730

chore: remove deprecated ItemStack location usage

---

.github/workflows/gradle.yml

while we have no secrets in CI that a compromised action could access, pinned versions ensure the shadow jar isn't compromised

chore: pin action versions for primary gradle workflow

---

CHANGELOG.md
src/main/java/dinkplugin/message/DiscordMessageHandler.java

See https://github.com/pajlads/DinkPlugin/issues/482#issuecomment-2136051003

fix(okhttp): follow redirect for status codes 307 and 308

---

CHANGELOG.md
docs/json-examples.md
src/main/java/dinkplugin/message/NotificationType.java
src/main/java/dinkplugin/notifiers/MetaNotifier.java
src/test/java/dinkplugin/notifiers/MetaNotifierTest.java

This pull request adds a logout message to the metadata notifier. This message will be sent when the gamestate changes from a gamestate that is considered to be in-game, to the "LOGIN_SCREEN" gamestate.
This notifier message intentionally includes no extra data. The only thing worth considering would've been the world, but that is expected to be included by default after PR #490, and knowing which world the player logs out from didn't seem all that useful anyway.
Closes #491

Add Logout notifier

---

CHANGELOG.md
docs/json-examples.md
src/main/java/dinkplugin/DinkPlugin.java
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/domain/ChatNotificationType.java
src/main/java/dinkplugin/notifiers/ChatNotifier.java
src/main/java/dinkplugin/notifiers/data/ChatNotificationData.java
src/test/java/dinkplugin/notifiers/ChatNotifierTest.java

Similar to #489 but for `NotificationFired`

feat(chat): allow matching on runelite notifications

---

.github/workflows/gradle7.yml

https://github.com/gradle/actions/blob/main/docs/deprecation-upgrade-guide.md#using-the-action-to-execute-gradle-via-the-arguments-parameter-is-deprecated

 chore(ci): avoid deprecated gradle arguments parameter

---

CHANGELOG.md
build.gradle.kts

Dink v1.10.2 most notably expands message sources for the chat notifier, augments notification metadata, and fixes some edge cases for the loot and death notifiers.

Release v1.10.2

---

src/main/java/dinkplugin/notifiers/GrandExchangeNotifier.java
src/main/java/dinkplugin/util/SerializedOffer.java

avoids clash of `SerializedOffer#equals(Object)` and `SerializedOffer#equals(GrandExchangeOffer)`, which was preventing lombok from generating `SerializedOffer#hashCode`

chore: resolve lombok warning

---

CHANGELOG.md
src/main/java/dinkplugin/message/DiscordMessageHandler.java
src/main/java/dinkplugin/message/Embed.java

Ensure discord notifications are fired for the following scenarios:
* safe deaths with `deathEmbedKeptItems` enabled (default: disabled), `deathIgnoreSafe` disabled (default: enabled), and 10+ items in inventory/equipment
* loot drop of 10+ items with `lootIcons` enabled (default: disabled)

fix: ensure embed count is within discord limit

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPlugin.java

avoids outdated notification data if players are disabling and enabling notifiers (while plugin remains enabled)
for example: disable level notifier, gain a level, later enable level notifier, get single xp drop for same skill => previously dink would trigger a level notif (tho level up occurred much earlier)

fix: clear particular notifier state when disabled

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/LevelNotifier.java
src/test/java/dinkplugin/notifiers/LevelNotifierTest.java

previously `INIT_GAME_TICKS` was effectively ignored since receiving skill data on first tick would set `shouldInit` to true
actually fixes #262
also simplifies some counter logic (atomic was overkill)

fix(level): avoid early initialization of skills

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/KillCountNotifier.java
src/main/java/dinkplugin/util/KillCountService.java
src/test/java/dinkplugin/notifiers/KillCountNotifierTest.java

I didn't actually test if the current implementation can handle a `<value>` with a comma in it, but here's the base change.

fix: parse killcount notifs over 999

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/GrandExchangeNotifier.java
src/main/java/dinkplugin/notifiers/KillCountNotifier.java

chore: avoid unconfigurable image embeds when rich embeds are disabled

---

CHANGELOG.md
docs/json-examples.md
src/main/java/dinkplugin/notifiers/LootNotifier.java
src/main/java/dinkplugin/notifiers/data/LootNotificationData.java
src/test/java/dinkplugin/notifiers/LootNotifierTest.java

feat: add npc id to loot metadata

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/ClueNotifier.java

feat: use thumbnail corresponding to clue difficulty

---

.github/workflows/update-resources.yml

no need for forks to get PRs when wiki updates

chore: disable scheduled resource updates on forks

---

CHANGELOG.md
docs/json-examples.md
src/main/java/dinkplugin/notifiers/KillCountNotifier.java
src/main/java/dinkplugin/notifiers/LootNotifier.java
src/main/java/dinkplugin/notifiers/data/BossNotificationData.java
src/main/java/dinkplugin/util/Utils.java
src/test/java/dinkplugin/notifiers/KillCountNotifierTest.java

Completes the party aspect of #585

 feat: add party to kc metadata

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/KillCountNotifier.java
src/main/java/dinkplugin/util/KillCountService.java
src/test/java/dinkplugin/notifiers/KillCountNotifierTest.java

Closes #585
References: https://dink.ivr.fi/2f50ef36fa91.png & https://dink.ivr.fi/2f1a91777a95.png

feat(kc): use challenge time for tob notifications

---

CHANGELOG.md
docs/json-examples.md

I noticed when reviewing the `json-examples.md` for the Kill Count payload structure it was missing `isPersonalBest` and `time`. This adds those two fields. Mainly, this will help show people what `ISO-8601` duration looks like.

feat: Include isPersonalBest & time in Kill Count JSON Example

---

CHANGELOG.md
docs/json-examples.md
src/main/java/dinkplugin/VersionManager.java
src/main/java/dinkplugin/notifiers/KillCountNotifier.java
src/main/java/dinkplugin/util/KillCountService.java
src/test/java/dinkplugin/notifiers/MatchersTest.java

Allows Heribobar kill counts to send kill count notifications. Wintertodt and Tempoross are acceptable so we should include Herbiboar to keep the "skilling" NPCs consistent. We should also consider adding Hunter Rumour completions.

feat: Add Herbiboar to Kill Count Notifier

---

CHANGELOG.md
src/main/java/dinkplugin/SettingsManager.java

Addresses https://github.com/pajlads/DinkPlugin/issues/594#issuecomment-2481589553

feat: refresh dynamic config if sufficiently old

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/LeaguesNotifier.java
src/test/java/dinkplugin/notifiers/LeaguesNotifierTest.java

https://oldschool.runescape.wiki/w/Raging_Echoes_League/Areas
dink is reporting wrong # tasks until next area unlock bc we aren't pulling these thresholds from cache

fix: manually update tasks for area unlock

---

gradle/wrapper/gradle-wrapper.properties
gradlew

https://docs.gradle.org/8.12/release-notes.html

chore: bump gradle wrapper to v8.12

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/SettingsManager.java
src/main/java/dinkplugin/domain/ChatPrivacyMode.java
src/main/java/dinkplugin/util/Utils.java

Requested @ https://discord.com/channels/301497432909414422/419891709883973642/1318802831397883915

feat: allow hiding just split dms from screenshots

---

CHANGELOG.md
docs/json-examples.md
src/main/java/dinkplugin/domain/LootCriteria.java
src/main/java/dinkplugin/notifiers/LootNotifier.java
src/main/java/dinkplugin/notifiers/data/AnnotatedItemStack.java
src/main/java/dinkplugin/notifiers/data/RareItemStack.java
src/test/java/dinkplugin/notifiers/LootNotifierTest.java

Closes #629
this change incurs a minor performance penalty since we now check the allowlist even for items that pass value/rarity threshold

feat: add loot criteria to extra metadata

---

.github/workflows/gradle-snapshot.yml

no need to disable the full build cache to grab the latest snapshot jar

ci(snapshot): allow some caching unrelated to dep versions

---

gradle/wrapper/gradle-wrapper.properties

https://docs.gradle.org/8.12.1/release-notes.html

chore: bump gradle wrapper to v8.12.1

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/LootNotifier.java

Rarity threshold set to zero with value-rarity intersection required would previously prevent any notifications; closes #646

fix(loot): ignore intersection if rarity threshold not set

---

CHANGELOG.md
src/main/java/dinkplugin/util/KillCountService.java

need loot tracker event for royal titans rather than NpcLootReceived https://github.com/runelite/runelite/commit/f76f4dc1f97f91681a36b28a147a2a32585456f6
npc id's are currently hardcoded until runelite pushes the next version so we can use the NpcID constant

feat: handle royal titans loot

---

CHANGELOG.md
docs/json-examples.md
src/main/java/dinkplugin/notifiers/KillCountNotifier.java
src/main/java/dinkplugin/notifiers/data/BossNotificationData.java
src/main/java/dinkplugin/util/KillCountService.java
src/test/java/dinkplugin/notifiers/KillCountNotifierTest.java

feat(kc): include pb time in metadata for normal kills

---

build.gradle.kts
src/test/java/dinkplugin/notifiers/LootNotifierTest.java
src/test/java/dinkplugin/notifiers/MockedNotifierTest.java
src/test/java/dinkplugin/util/IndexedArray.java

https://github.com/runelite/runelite/commit/0f8689a776030c77c9aea95ae3d3c221312c70a3#diff-4b98c5156db03c0fb9fe9ea32e07a6becdaa03b2c2fade624a3096f91fa9a6b9

chore: fix test compilation after IndexedObjectSet change

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/notifiers/LootNotifier.java

feat: allow filtering ba gambles from loot notifier

---

CHANGELOG.md
README.md
docs/external-plugin-messaging.md
docs/json-examples.md
src/main/java/dinkplugin/DinkPlugin.java
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/domain/ExternalNotificationRequest.java
src/main/java/dinkplugin/domain/ExternalScreenshotPolicy.java
src/main/java/dinkplugin/message/DiscordMessageHandler.java
src/main/java/dinkplugin/message/Embed.java
src/main/java/dinkplugin/message/Field.java
src/main/java/dinkplugin/message/NotificationBody.java
src/main/java/dinkplugin/message/NotificationType.java
src/main/java/dinkplugin/message/templating/Template.java
src/main/java/dinkplugin/message/templating/impl/SimpleReplacement.java
src/main/java/dinkplugin/notifiers/ExternalPluginNotifier.java
src/main/java/dinkplugin/notifiers/data/ExternalNotificationData.java
src/main/java/dinkplugin/util/HttpUrlAdapter.java
src/main/java/dinkplugin/util/Utils.java
src/main/java/dinkplugin/util/WorldUtils.java
src/test/java/dinkplugin/notifiers/ExternalPluginNotifierTest.java
src/test/java/dinkplugin/notifiers/MockedNotifierTest.java
src/test/java/dinkplugin/notifiers/PlayerKillNotifierTest.java

feat: add notifier for external plugins

---

CHANGELOG.md
build.gradle.kts

Dink v1.11.0 allows other plugins to trigger webhook notifications via `PluginMessage`

Release v1.11.0

---

CHANGELOG.md
src/main/java/dinkplugin/domain/ExternalNotificationRequest.java
src/main/java/dinkplugin/notifiers/ExternalPluginNotifier.java
src/test/java/dinkplugin/notifiers/ExternalPluginNotifierTest.java

ensures external plugins can't evade the code scanner by providing `List<String>` instead of `List<HttpUrl>`

fix(external): harden url input validation

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/ExternalPluginNotifier.java
src/test/java/dinkplugin/notifiers/ExternalPluginNotifierTest.java

Fixes first part of #675
Not 100% sure if this is the most optimal approach, but it seems ok

fix(external): Allow null replacements

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPlugin.java

this is intended to be combined with lalochazia/missed-clues#2 to prevent erroneous pet events
maybe it should affect `chatNotifier.onMessage` too? not sure enough on that one

filter out plugin-sourced chat messages

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/DeathNotifier.java
src/test/java/dinkplugin/notifiers/DeathNotifierTest.java

Updates the `%VALUELOST%` to be a formatted value. Closes #708

feat: Add Delimiter to DeathNotifier

---

CHANGELOG.md
build.gradle.kts

Dink v1.11.7 migrates to gameval constants
https://github.com/pajlads/DinkPlugin/compare/v1.11.6...chore/release-1.11.7

Release v1.11.7

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/PetNotifier.java

cook made a reddit post the other day about the post-nerf droprates, and yami is still 1/2500 as of today

chore(pet): add Yami drop rate

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/LootNotifier.java
src/main/java/dinkplugin/util/KillCountService.java
src/test/java/dinkplugin/notifiers/LootNotifierTest.java

First contribution ever, not sure if this is remotely close to the solution or not.
[Issue #744](https://github.com/pajlads/DinkPlugin/issues/744) is something I've noticed myself, looks like the loot tracking for **The Gauntlet** has changed to **Corrupted Hunllef**, I'm not sure if this results it in becoming a special loot NPC or not.
Not sure what other implications this brings if it is in fact this issue.

fix: fire gauntlet loot notifications after rl change

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/MetaNotifier.java

Add isEnabled check to onVarbit as it was firing without metadata handler being filled out
Fixes https://github.com/pajlads/DinkPlugin/issues/755

fix(metanotifier): Make onVarbit check for isEnabled

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/GrandExchangeNotifier.java

avoids calling `AccountTypeTracker` before it is ready (and prevents screenshot before user has clicked play button)

fix: delay ge notifications on login

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPlugin.java

fix: use jagex loot event for hallowed sepulchre
