src/main/java/universalDiscord/UniversalDiscordPlugin.java

As noted in the original README - %POINTS% is supposed to output the received points, but currently it outputs your total points.
This fixes that. (probably)

Fix %POINTS% outputting total points instead of points recieved

---

src/test/java/dink/test.kt

Ensure that the matched task group from `SLAYER_TASK_REGEX` yields the expected result

chore(test): ensure slayer task match is accurate

---

src/main/java/dinkplugin/DinkPlugin.java
src/main/java/dinkplugin/LevelNotifier.java

Fix levelup notifications always firing

---

src/main/java/dinkplugin/ClueNotifier.java
src/main/java/dinkplugin/CollectionNotifier.java
src/main/java/dinkplugin/DeathNotifier.java
src/main/java/dinkplugin/DinkPlugin.java
src/main/java/dinkplugin/LevelNotifier.java
src/main/java/dinkplugin/LootNotifier.java
src/main/java/dinkplugin/QuestNotifier.java
src/main/java/dinkplugin/SlayerNotifier.java

 Ignore notifications in speedrun worlds

---

src/main/java/dinkplugin/DinkPlugin.java
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/NotificationType.java
src/main/java/dinkplugin/QuestNotifier.java
src/main/java/dinkplugin/SpeedrunNotificationData.java
src/main/java/dinkplugin/SpeedrunNotifier.java
src/main/java/dinkplugin/SpeedrunPBNotificationData.java
src/main/java/dinkplugin/Utils.java

Needs a tiny bit of name changes in the code

Add speedrun notifications

---

src/main/java/dinkplugin/ClueNotifier.java
src/main/java/dinkplugin/DinkPlugin.java
src/main/java/dinkplugin/LevelNotifier.java
src/main/java/dinkplugin/SlayerNotifier.java
src/test/java/dinkplugin/MatchersTest.kt

* collection variable type can be more general than the specific implementation (e.g., `Map` instead of `HashMap`)
* `Hashtable` should be avoided
* use getters/setters instead of public class fields
* resolve some generics warnings

refactor: general code cleanup

---

runelite-plugin.properties
src/main/java/dinkplugin/DinkPlugin.java

Both these files need to be updated
Fixes #22

Update description & tags

---

src/main/java/dinkplugin/DinkPlugin.java

Addresses https://github.com/MidgetJake/UniversalDiscordNotifier/issues/10

fix: avoid death notifications for actors with the same name

---

src/main/java/dinkplugin/DinkPlugin.java
src/main/java/dinkplugin/LevelNotifier.java

Closes #31 (related upstream issue: https://github.com/MidgetJake/UniversalDiscordNotifier/issues/17)

feat: notify on virtual level ups

---

README.md
src/main/java/dinkplugin/ClueNotifier.java
src/main/java/dinkplugin/LootNotifier.java

feat: add total value pattern for loot and clue scrolls

---

src/main/java/dinkplugin/ClueNotifier.java
src/main/java/dinkplugin/CollectionNotifier.java
src/main/java/dinkplugin/DeathNotifier.java
src/main/java/dinkplugin/DinkPlugin.java
src/main/java/dinkplugin/LevelNotifier.java
src/main/java/dinkplugin/LootNotifier.java
src/main/java/dinkplugin/QuestNotifier.java
src/main/java/dinkplugin/SlayerNotifier.java
src/test/java/dinkplugin/IgnoredWorldTest.kt

Addresses https://github.com/ATremonte/Discord-Level-Notifications/issues/5

fix: ignore more world types

---

CHANGELOG.md
build.gradle.kts
src/main/java/dinkplugin/message/NotificationBody.java

* Remove `@Singular` due to outdated lombok from runelite (the patch is in 1.18.22)
* Update runelite to 1.9.3

fix: avoid @Singular due to outdated lombok from runelite

---

build.gradle.kts

Added steps for how-to-release and then forgot to follow them

Bump build version to v1.0.3

---

CHANGELOG.md
README.md
src/main/java/dinkplugin/DinkPlugin.java
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/Utils.java
src/main/java/dinkplugin/message/NotificationType.java
src/main/java/dinkplugin/notifiers/KillCountNotifier.java
src/main/java/dinkplugin/notifiers/data/BossNotificationData.java
src/test/java/dinkplugin/notifiers/MatchersTest.java

feat: add kill count notifier

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/notifiers/SlayerNotifier.java

feat: add slayer point threshold for notifications

---

CHANGELOG.md
README.md
src/main/java/dinkplugin/DinkPlugin.java
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/domain/AchievementDiaries.java
src/main/java/dinkplugin/message/NotificationType.java
src/main/java/dinkplugin/notifiers/DiaryNotifier.java
src/main/java/dinkplugin/notifiers/data/DiaryNotificationData.java
src/test/java/dinkplugin/domain/AchievementDiariesTest.java

feat: add achievement diary notifier

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPlugin.java
src/main/java/dinkplugin/message/DiscordMessageHandler.java
src/main/java/dinkplugin/notifiers/BaseNotifier.java
src/main/java/dinkplugin/notifiers/ClueNotifier.java
src/main/java/dinkplugin/notifiers/CollectionNotifier.java
src/main/java/dinkplugin/notifiers/CombatTaskNotifier.java
src/main/java/dinkplugin/notifiers/DeathNotifier.java
src/main/java/dinkplugin/notifiers/DiaryNotifier.java
src/main/java/dinkplugin/notifiers/KillCountNotifier.java
src/main/java/dinkplugin/notifiers/LevelNotifier.java
src/main/java/dinkplugin/notifiers/LootNotifier.java
src/main/java/dinkplugin/notifiers/PetNotifier.java
src/main/java/dinkplugin/notifiers/QuestNotifier.java
src/main/java/dinkplugin/notifiers/SlayerNotifier.java
src/main/java/dinkplugin/notifiers/SpeedrunNotifier.java

Avoid hard dependencies to allow for easier testing/mocking in the future (also this is more idiomatic for runelite)

refactor: use more dependency injection

---

CHANGELOG.md
src/main/java/dinkplugin/Utils.java
src/main/java/dinkplugin/notifiers/LootNotifier.java
src/test/java/dinkplugin/notifiers/ClueNotifierTest.java
src/test/java/dinkplugin/notifiers/CollectionNotifierTest.java
src/test/java/dinkplugin/notifiers/CombatTaskNotifierTest.java
src/test/java/dinkplugin/notifiers/DeathNotifierTest.java
src/test/java/dinkplugin/notifiers/DiaryNotifierTest.java
src/test/java/dinkplugin/notifiers/KillCountNotifierTest.java
src/test/java/dinkplugin/notifiers/LevelNotifierTest.java
src/test/java/dinkplugin/notifiers/LootNotifierTest.java
src/test/java/dinkplugin/notifiers/MockedNotifierTest.java
src/test/java/dinkplugin/notifiers/PetNotifierTest.java
src/test/java/dinkplugin/notifiers/QuestNotifierTest.java
src/test/java/dinkplugin/notifiers/SlayerNotifierTest.java
src/test/java/dinkplugin/notifiers/SpeedrunNotifierTest.java

* For each notifier, ensure no message is sent if the notifier is disabled in config
* Add more interesting test cases for death notifier

chore: add more mock notifier tests

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/message/DiscordMessageHandler.java
src/main/java/dinkplugin/notifiers/BaseNotifier.java
src/main/java/dinkplugin/notifiers/ClueNotifier.java
src/main/java/dinkplugin/notifiers/CollectionNotifier.java
src/main/java/dinkplugin/notifiers/CombatTaskNotifier.java
src/main/java/dinkplugin/notifiers/DeathNotifier.java
src/main/java/dinkplugin/notifiers/DiaryNotifier.java
src/main/java/dinkplugin/notifiers/KillCountNotifier.java
src/main/java/dinkplugin/notifiers/LevelNotifier.java
src/main/java/dinkplugin/notifiers/LootNotifier.java
src/main/java/dinkplugin/notifiers/PetNotifier.java
src/main/java/dinkplugin/notifiers/QuestNotifier.java
src/main/java/dinkplugin/notifiers/SlayerNotifier.java
src/main/java/dinkplugin/notifiers/SpeedrunNotifier.java
src/test/java/dinkplugin/notifiers/ClueNotifierTest.java
src/test/java/dinkplugin/notifiers/CollectionNotifierTest.java
src/test/java/dinkplugin/notifiers/CombatTaskNotifierTest.java
src/test/java/dinkplugin/notifiers/DeathNotifierTest.java
src/test/java/dinkplugin/notifiers/DiaryNotifierTest.java
src/test/java/dinkplugin/notifiers/KillCountNotifierTest.java
src/test/java/dinkplugin/notifiers/LevelNotifierTest.java
src/test/java/dinkplugin/notifiers/LootNotifierTest.java
src/test/java/dinkplugin/notifiers/MockedNotifierTest.java
src/test/java/dinkplugin/notifiers/PetNotifierTest.java
src/test/java/dinkplugin/notifiers/QuestNotifierTest.java
src/test/java/dinkplugin/notifiers/SlayerNotifierTest.java
src/test/java/dinkplugin/notifiers/SpeedrunNotifierTest.java

feat: allow notifier-specific webhook url overrides

---

CHANGELOG.md
src/main/java/dinkplugin/message/DiscordMessageHandler.java
src/main/java/dinkplugin/message/NotificationBody.java
src/main/java/dinkplugin/notifiers/ClueNotifier.java
src/main/java/dinkplugin/notifiers/CollectionNotifier.java
src/main/java/dinkplugin/notifiers/CombatTaskNotifier.java
src/main/java/dinkplugin/notifiers/DeathNotifier.java
src/main/java/dinkplugin/notifiers/DiaryNotifier.java
src/main/java/dinkplugin/notifiers/KillCountNotifier.java
src/main/java/dinkplugin/notifiers/LevelNotifier.java
src/main/java/dinkplugin/notifiers/LootNotifier.java
src/main/java/dinkplugin/notifiers/PetNotifier.java
src/main/java/dinkplugin/notifiers/QuestNotifier.java
src/main/java/dinkplugin/notifiers/SlayerNotifier.java
src/main/java/dinkplugin/notifiers/SpeedrunNotifier.java

refactor: use notifier-specific screenshot filename

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPlugin.java
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/Utils.java
src/main/java/dinkplugin/notifiers/LootNotifier.java
src/test/java/dinkplugin/notifiers/LootNotifierTest.java

Add a setting for loot notifier to ignore player loot events

feat: add loot notifier option to skip player loot

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/SlayerNotifier.java
src/test/java/dinkplugin/notifiers/SlayerNotifierTest.java

fix: ensure boss name is in slayer task message

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/notifiers/LevelNotifier.java

feat: add setting to ignore small level ups

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/notifiers/BaseNotifier.java
src/main/java/dinkplugin/notifiers/ClueNotifier.java
src/main/java/dinkplugin/notifiers/LootNotifier.java

feat: add min items value setting for send image

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/BaseNotifier.java
src/main/java/dinkplugin/notifiers/ClueNotifier.java
src/main/java/dinkplugin/notifiers/CollectionNotifier.java
src/main/java/dinkplugin/notifiers/CombatTaskNotifier.java
src/main/java/dinkplugin/notifiers/DeathNotifier.java
src/main/java/dinkplugin/notifiers/DiaryNotifier.java
src/main/java/dinkplugin/notifiers/KillCountNotifier.java
src/main/java/dinkplugin/notifiers/LevelNotifier.java
src/main/java/dinkplugin/notifiers/LootNotifier.java
src/main/java/dinkplugin/notifiers/PetNotifier.java
src/main/java/dinkplugin/notifiers/QuestNotifier.java
src/main/java/dinkplugin/notifiers/SlayerNotifier.java
src/main/java/dinkplugin/notifiers/SpeedrunNotifier.java

Follow up from https://github.com/pajlads/DinkPlugin/pull/98#discussion_r1053400756

refactor: avoid lambda for sendImage in BaseNotifier

---

CHANGELOG.md
runelite-plugin.properties
src/main/java/dinkplugin/DinkPlugin.java

Added a tag for the functionalities added in #63 and #67 
I couldn't think of a good tag for Boss Kill Counts so I just skipped it 🎳

Add more plugin-hub search tags

---

.github/dependabot.yml

Add Dependabot to update GitHub Actions workflows

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/notifiers/DeathNotifier.java
src/test/java/dinkplugin/notifiers/DeathNotifierTest.java

feat: add toggle for protected items on death embed

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPlugin.java
src/main/java/dinkplugin/SettingsValidator.java
src/main/java/dinkplugin/message/DiscordMessageHandler.java
src/main/java/dinkplugin/notifiers/BaseNotifier.java
src/main/java/dinkplugin/notifiers/ClueNotifier.java
src/main/java/dinkplugin/notifiers/CollectionNotifier.java
src/main/java/dinkplugin/notifiers/CombatTaskNotifier.java
src/main/java/dinkplugin/notifiers/DeathNotifier.java
src/main/java/dinkplugin/notifiers/DiaryNotifier.java
src/main/java/dinkplugin/notifiers/KillCountNotifier.java
src/main/java/dinkplugin/notifiers/LevelNotifier.java
src/main/java/dinkplugin/notifiers/LootNotifier.java
src/main/java/dinkplugin/notifiers/PetNotifier.java
src/main/java/dinkplugin/notifiers/QuestNotifier.java
src/main/java/dinkplugin/notifiers/SlayerNotifier.java
src/main/java/dinkplugin/notifiers/SpeedrunNotifier.java
src/main/java/dinkplugin/util/ItemUtils.java
src/main/java/dinkplugin/util/QuestUtils.java
src/main/java/dinkplugin/util/TimeUtils.java
src/main/java/dinkplugin/util/Utils.java
src/main/java/dinkplugin/util/WorldUtils.java
src/test/java/dinkplugin/IgnoredWorldTest.java
src/test/java/dinkplugin/UtilsTest.java
src/test/java/dinkplugin/notifiers/DeathNotifierTest.java
src/test/java/dinkplugin/notifiers/KillCountNotifierTest.java

Split up `Utils` into `ItemUtils`, `QuestUtils`, `TimeUtils`, `WorldUtils` for cleanliness
https://www.javadoc.io/doc/org.projectlombok/lombok/latest/lombok/experimental/UtilityClass.html

refactor: split up Utils

---

CHANGELOG.md
src/main/java/dinkplugin/message/DiscordMessageHandler.java
src/main/java/dinkplugin/message/NotificationBody.java
src/main/java/dinkplugin/message/NotificationType.java
src/main/java/dinkplugin/notifiers/LevelNotifier.java

<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>

feat: use skill icon in level up embed

---

CHANGELOG.md
README.md

https://github.com/Felanbird/DinkPlugin/blob/chore/use-collapsible-markdown-for-readme/README.md
~~- [ ] Add missing stuff?~~ later

Update the README to be less confusing to users

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/notifiers/LevelNotifier.java
src/test/java/dinkplugin/notifiers/LevelNotifierTest.java

feat: add setting to ignore virtual levels

---

CHANGELOG.md
README.md
src/main/java/dinkplugin/notifiers/CollectionNotifier.java
src/main/java/dinkplugin/notifiers/data/CollectionNotificationData.java
src/main/java/dinkplugin/util/ItemSearcher.java
src/main/java/dinkplugin/util/ItemUtils.java
src/main/java/dinkplugin/util/Utils.java
src/test/java/dinkplugin/notifiers/CollectionNotifierTest.java
src/test/java/dinkplugin/util/ItemSearcherTest.java

I highly suspect the code needs some more work. But this feature simply adds the item as a thumbnail to the collection log notifier. When something goes wrong it will still use the boring collection log book as fallback thumb.
Also I won't be able to fix any comments till probably next weekend. So feel free to improve this PR 😋

Added ItemSearcher that can find item urls based on name.

---

CHANGELOG.md
README.md

* Updated introduction
* Add explanation for each notifier
* Add missing docs for pet and speedrun notifiers
* Highlight some advanced features

chore: document pet and speedrun notifiers in readme

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/domain/ClueTier.java
src/main/java/dinkplugin/notifiers/ClueNotifier.java
src/test/java/dinkplugin/notifiers/ClueNotifierTest.java

feat: add min clue tier setting

---

CHANGELOG.md
src/main/java/dinkplugin/domain/PlayerLookupService.java
src/test/java/dinkplugin/notifiers/MockedNotifierTest.java

fix: escape player name in author url

---

.github/workflows/gradle.yml

In case users need more instructions

chore: clarify nightly build usage

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPluginConfig.java

chore: use units annotation in config

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPlugin.java
src/main/java/dinkplugin/notifiers/DiaryNotifier.java
src/test/java/dinkplugin/notifiers/DiaryNotifierTest.java

Should help with #93. Thanks to DvH for the idea

feat: parse diary completion from message box

---

CHANGELOG.md
README.md
src/main/java/dinkplugin/DinkPlugin.java
src/main/java/dinkplugin/SettingsManager.java
src/main/java/dinkplugin/util/ConfigUtil.java
src/main/java/dinkplugin/util/Utils.java
src/test/java/dinkplugin/notifiers/MockedNotifierTest.java

feat: add config import and export commands

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/DiaryNotifier.java
src/main/java/dinkplugin/util/Utils.java
src/test/java/dinkplugin/notifiers/DiaryNotifierTest.java

Fixes https://github.com/pajlads/DinkPlugin/pull/157#issuecomment-1416518570

fix: loosen diary area matching from message box

---

CHANGELOG.md
build.gradle.kts
gradle/wrapper/gradle-wrapper.properties

https://docs.gradle.org/8.0/release-notes.html

chore: update gradle to v8.0

---

CHANGELOG.md
README.md
src/main/java/dinkplugin/message/Field.java
src/main/java/dinkplugin/notifiers/PetNotifier.java
src/main/java/dinkplugin/notifiers/data/LevelNotificationData.java
src/main/java/dinkplugin/notifiers/data/PetNotificationData.java
src/main/java/dinkplugin/util/ItemUtils.java
src/test/java/dinkplugin/notifiers/PetNotifierTest.java

feat: parse pet acquisition milestone

---

CHANGELOG.md
README.md
src/main/java/dinkplugin/DinkPlugin.java
src/main/java/dinkplugin/notifiers/CollectionNotifier.java
src/main/java/dinkplugin/notifiers/data/CollectionNotificationData.java
src/test/java/dinkplugin/notifiers/CollectionNotifierTest.java

feat(collection): include number of completed entries

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPluginConfig.java

chore: collapse notifier settings by default

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPlugin.java
src/main/java/dinkplugin/notifiers/CollectionNotifier.java

Follow-up from https://github.com/pajlads/DinkPlugin/pull/174 & https://github.com/pajlads/DinkPlugin/pull/178#discussion_r1116627483

fix(collection): reset counts when logged out

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPlugin.java
src/main/java/dinkplugin/SettingsManager.java
src/main/java/dinkplugin/util/ConfigUtil.java
src/main/java/dinkplugin/util/Utils.java

fix: avoid false settings warnings on world hops

---

CHANGELOG.md
README.md
src/main/java/dinkplugin/notifiers/DeathNotifier.java
src/main/java/dinkplugin/notifiers/LootNotifier.java
src/main/java/dinkplugin/util/WorldUtils.java
src/test/java/dinkplugin/notifiers/DeathNotifierTest.java

Closes #188 (but not toggleable)
https://oldschool.runescape.wiki/w/Minigames#Safe

fix(death): ignore more safe areas

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/PetNotifier.java
src/test/java/dinkplugin/notifiers/PetNotifierTest.java

fix: delay pet notifications for milestone

---

CHANGELOG.md
README.md
src/main/java/dinkplugin/notifiers/LootNotifier.java
src/main/java/dinkplugin/notifiers/data/LootNotificationData.java
src/test/java/dinkplugin/notifiers/LootNotifierTest.java

feat: include loot category in extra data

---

CHANGELOG.md
README.md
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/message/DiscordMessageHandler.java
src/main/java/dinkplugin/message/Embed.java
src/main/java/dinkplugin/util/Utils.java
src/test/java/dinkplugin/notifiers/MockedNotifierTest.java

Closes #199
Related https://github.com/MidgetJake/UniversalDiscordNotifier/issues/35

feat: rescale images to comply with discord size limit

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/DeathNotifier.java

Refactor portion of #191 to work towards #189 (next PR will allow NPC attribution)

refactor(death): generify identifyPker

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/QuestNotifier.java
src/main/java/dinkplugin/util/QuestUtils.java

fix(quest): ignore partial completions

---

CHANGELOG.md
gradle/wrapper/gradle-wrapper.properties

https://docs.gradle.org/8.1.1/release-notes.html

chore: bump gradle to v8.1.1

---

CHANGELOG.md
README.md
src/main/java/dinkplugin/DinkPlugin.java
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/message/NotificationType.java
src/main/java/dinkplugin/notifiers/PlayerKillNotifier.java
src/main/java/dinkplugin/notifiers/data/PkNotificationData.java
src/main/java/dinkplugin/notifiers/data/PlayerKillNotificationData.java
src/main/java/dinkplugin/util/ItemUtils.java
src/main/java/dinkplugin/util/WorldUtils.java
src/test/java/dinkplugin/notifiers/PlayerKillNotifierTest.java

```json
{
"type":"PLAYER_KILL",
"playerName":"dankgg",
"accountType":"NORMAL",
"extra":{
"name":"Shipy",
"combatLevel":74,
"equipment":{
"AMULET":{
"id":1731,
"quantity":1,
"priceEach":1987,
"name":"Amulet of power"
},
"WEAPON":{
"id":1333,
"quantity":1,
"priceEach":14971,
"name":"Rune scimitar"
},
"TORSO":{
"id":1135,
"quantity":1,
"priceEach":4343,
"name":"Green d\u0027hide body"
},
"LEGS":{
"id":1099,
"quantity":1,
"priceEach":2077,
"name":"Green d\u0027hide chaps"
},
"HANDS":{
"id":1065,
"quantity":1,
"priceEach":1392,
"name":"Green d\u0027hide vambraces"
}
},
"world":394,
"location":{
"x":3334,
"y":4761,
"plane":0
},
"myHitpoints":20,
"myLastDamage":12
}
}
```

feat: add player kill notifier

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/notifiers/DeathNotifier.java
src/test/java/dinkplugin/notifiers/DeathNotifierTest.java

For folks who want death notifications in safe areas (requested by a user)

feat: add setting to notify on safe deaths

---

.github/workflows/gradle.yml
.github/workflows/lint.yml
.prettierignore
.prettierrc.yaml
README.md

- Add prettier config files
- Run prettier on project
- Add lint job

Run prettier on project

---

CHANGELOG.md
README.md
src/main/java/dinkplugin/DinkPlugin.java
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/message/NotificationType.java
src/main/java/dinkplugin/notifiers/GroupStorageNotifier.java
src/main/java/dinkplugin/notifiers/data/GroupStorageNotificationData.java
src/test/java/dinkplugin/notifiers/GroupStorageNotifierTest.java
src/test/java/dinkplugin/notifiers/MockedNotifierTest.java

feat: add group iron shared storage notifier

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/notifiers/LootNotifier.java

feat(loot): use item image as rich embed thumbnail

---

CHANGELOG.md
src/main/java/dinkplugin/domain/AccountType.java
src/main/java/dinkplugin/message/DiscordMessageHandler.java
src/main/java/dinkplugin/message/NotificationBody.java
src/main/java/dinkplugin/notifiers/DeathNotifier.java
src/main/java/dinkplugin/util/Utils.java
src/main/java/dinkplugin/util/WorldUtils.java
src/test/java/dinkplugin/notifiers/GroupStorageNotifierTest.java
src/test/java/dinkplugin/notifiers/MockedNotifierTest.java

refactor: avoid deprecated RL AccountType enum

---

CHANGELOG.md
README.md
src/main/java/dinkplugin/DinkPlugin.java
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/notifiers/CombatTaskNotifier.java
src/main/java/dinkplugin/notifiers/data/CombatAchievementData.java
src/test/java/dinkplugin/notifiers/CombatTaskNotifierTest.java

Tracks total points achieved and next unlock progress via varbits (and calculations)

feat: track combat task points unlock progress

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/notifiers/GroupStorageNotifier.java
src/test/java/dinkplugin/notifiers/GroupStorageNotifierTest.java

feat: allow exclusion of group name in gim storage notifications

---

CHANGELOG.md
src/main/java/dinkplugin/util/WorldUtils.java

Enabled by https://github.com/runelite/runelite/commit/0b277e2ee07209e2f35a9b6a2442e24d69f32cf5

fix: skip notifications from beta worlds

---

CHANGELOG.md
src/main/java/dinkplugin/message/templating/Replacements.java
src/main/java/dinkplugin/notifiers/PlayerKillNotifier.java
src/test/java/dinkplugin/message/templating/TemplateTest.java
src/test/java/dinkplugin/notifiers/PlayerKillNotifierTest.java

Follow-up from #243 
* https://secure.runescape.com/m=hiscore_oldschool/hiscorepersonal?user1=Romy

feat(pk): link target name to player lookup service

---

CHANGELOG.md
README.md

docs: fix step skipping information not having its own line

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/DeathNotifier.java
src/test/java/dinkplugin/notifiers/DeathNotifierItemTest.java

fix(death): unstack items for kept or lost classification

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/LevelNotifier.java

Fixes #262
Cannot reproduce the normal log in bug now, or the hop from pvp world/speedrun world anymore

Increase delay of skill initialization

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/LevelNotifier.java
src/test/java/dinkplugin/notifiers/LevelNotifierTest.java

chore(level): remove Skill.OVERALL usage

---

.github/workflows/gradle7.yml
CHANGELOG.md

Suggested in https://github.com/pajlads/DinkPlugin/pull/263#issuecomment-1615266723

chore: add gradle 7 build action

---

CHANGELOG.md
gradle/wrapper/gradle-wrapper.properties

https://docs.gradle.org/8.2.1/release-notes.html

chore: bump gradle wrapper to v8.2.1

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/message/DiscordMessageHandler.java
src/main/java/dinkplugin/message/NotificationBody.java

feat: include clan name in notification metadata

---

CHANGELOG.md
README.md
src/main/java/dinkplugin/notifiers/LevelNotifier.java
src/main/java/dinkplugin/notifiers/data/LevelNotificationData.java
src/test/java/dinkplugin/notifiers/LevelNotifierTest.java

feat(level): send notification upon 200M xp

---

CHANGELOG.md
README.md
src/main/java/dinkplugin/DinkPlugin.java
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/message/NotificationType.java
src/main/java/dinkplugin/notifiers/GrandExchangeNotifier.java
src/main/java/dinkplugin/notifiers/data/GrandExchangeNotificationData.java
src/test/java/dinkplugin/notifiers/GrandExchangeNotifierTest.java
src/test/java/dinkplugin/notifiers/MockedNotifierTest.java

Closes #272 (Related: https://github.com/OkayestDev/OSRS-Flipper/issues/18)
Current rules:
* Transaction must exceed min value
* Cancellation is not notified unless enabled in config
* Partial progress is not notified unless spacing minutes have passed
Required feedback:
* Are the above rules reasonable
* Do the rich embed fields need any changes
* Does more real-world testing reveal any edge cases
Sample:
```json
{
"type": "GRAND_EXCHANGE",
"playerName": "dankgg",
"accountType": "NORMAL",
"extra": {
"slot": 2,
"status": "BOUGHT",
"item": {
"id": 314,
"quantity": 2,
"priceEach": 3,
"name": "Feather"
},
"marketPrice": 2,
"targetQuantity": 2
},
"embeds": [
{
"title": "Grand Exchange",
"description": "dankgg bought 2 x [Feather](https://oldschool.runescape.wiki/w/Special:Search?search=Feather …
```

feat: add grand exchange trade notifier

---

CHANGELOG.md
build.gradle.kts

DT2 support & config export fix for new webhook overrides

Release Dink v1.6.1

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/GrandExchangeNotifier.java

fix(ge): avoid duplicate partial trade notifications

---

CHANGELOG.md
build.gradle.kts

GE bug that was just annoying enough we might as well slap it into the existing PR

Release v1.6.2

---

CHANGELOG.md
README.md
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/notifiers/LevelNotifier.java
src/test/java/dinkplugin/notifiers/LevelNotifierTest.java

feat: add %TOTAL_LEVEL% template for level message

---

CHANGELOG.md
README.md
src/main/java/dinkplugin/notifiers/PetNotifier.java
src/main/java/dinkplugin/notifiers/data/PetNotificationData.java
src/test/java/dinkplugin/notifiers/PetNotifierTest.java

feat: indicate duplicate pet drops

---

CHANGELOG.md
README.md
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/message/DiscordErrorMessage.java
src/main/java/dinkplugin/message/DiscordMessageHandler.java
src/main/java/dinkplugin/message/NotificationBody.java
src/main/java/dinkplugin/message/templating/Evaluable.java
src/main/java/dinkplugin/util/Utils.java
src/test/java/dinkplugin/notifiers/MockedNotifierTest.java
src/test/java/dinkplugin/util/UtilsTest.java

Closes #294
List view:
Gallery view:

feat: allow discord forum thread creation

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/notifiers/PetNotifier.java
src/test/java/dinkplugin/notifiers/PetNotifierTest.java

feat(pet): clarify duplicate status for non-rich webhook messages

---

CHANGELOG.md
README.md
src/main/java/dinkplugin/DinkPlugin.java
src/main/java/dinkplugin/notifiers/CollectionNotifier.java
src/main/java/dinkplugin/util/ConfigUtil.java
src/main/java/dinkplugin/util/Utils.java
src/test/java/dinkplugin/notifiers/CollectionNotifierTest.java

feat: capture collection log popup widget

---

CHANGELOG.md
README.md
src/main/java/dinkplugin/DinkPlugin.java
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/notifiers/KillCountNotifier.java
src/test/java/dinkplugin/notifiers/KillCountNotifierTest.java

feat: send penance queen kills as kc notification

---

CHANGELOG.md
README.md
src/main/java/dinkplugin/DinkPlugin.java
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/SettingsManager.java
src/main/java/dinkplugin/notifiers/LootNotifier.java
src/main/java/dinkplugin/util/ItemUtils.java
src/test/java/dinkplugin/notifiers/LootNotifierTest.java

Allowlist: useful for bingo events or untradeable drops below gp threshold
Denylist: useful to ignore common drops that exceed gp threshold

feat(loot): add item allowlist and denylist

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/notifiers/LootNotifier.java
src/main/java/dinkplugin/util/Utils.java
src/test/java/dinkplugin/notifiers/LootNotifierTest.java
src/test/java/dinkplugin/util/UtilsTest.java

Follow-up from https://github.com/pajlads/DinkPlugin/pull/310#pullrequestreview-1618701724

feat: support wildcard in loot item filters

---

build.gradle.kts

Has no impact on plugin hub
https://projectlombok.org/changelog

chore: bump lombok to v1.8.30

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPlugin.java
src/main/java/dinkplugin/domain/AccountType.java
src/main/java/dinkplugin/notifiers/DeathNotifier.java
src/main/java/dinkplugin/util/WorldUtils.java
src/test/java/dinkplugin/notifiers/DeathNotifierTest.java

fix: classify toa attempts as safe deaths

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/KillCountNotifier.java
src/test/java/dinkplugin/notifiers/KillCountNotifierTest.java

fix(pb): use correct challenge duration for gauntlet kills

---

.github/ISSUE_TEMPLATE/a_make_a_report.yml
.github/ISSUE_TEMPLATE/b_make_a_suggestion.yml

Closes #125
test here: https://github.com/Felanbird-chatterino7/DinkPlugin/issues/new/choose

Add `Issues` templates

---

CHANGELOG.md
src/main/java/dinkplugin/util/WorldUtils.java

fix: consider galvek rematches as safe deaths

---

CHANGELOG.md
src/main/java/dinkplugin/util/WorldUtils.java

https://github.com/runelite/runelite/commit/c354f9f994c824dc2a78f6acfc445689adf45f1d

refactor: fix lms check

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/LeaguesNotifier.java
src/test/java/dinkplugin/notifiers/LeaguesNotifierTest.java

fix: report correct tasks until next area unlock

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPlugin.java
src/main/java/dinkplugin/notifiers/LootNotifier.java
src/test/java/dinkplugin/notifiers/LootNotifierTest.java

https://github.com/runelite/runelite/commit/875b7fe7924eeb92ada77b688d7f43a495e7e345

chore: use runelite unsired loot event instead of our widget handler

---

CHANGELOG.md
README.md
src/main/java/dinkplugin/notifiers/LeaguesNotifier.java
src/main/java/dinkplugin/notifiers/data/LeaguesRelicNotificationData.java
src/main/java/dinkplugin/notifiers/data/LeaguesTaskNotificationData.java
src/test/java/dinkplugin/notifiers/LeaguesNotifierTest.java

just the simple parts from #368

refactor: minor changes to leagues code

---

CHANGELOG.md
build.gradle.kts

changes one actual thing which I went ahead and actually tested, hiding private chat seems to still work, also adds a chrimbus logo

Release v1.8.1

---

CHANGELOG.md
build.gradle.kts

Release v1.8.2

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/PetNotifier.java

https://oldschool.runescape.wiki/w/Scurry

chore: add scurrius pet handling

---

CHANGELOG.md
README.md
src/main/java/dinkplugin/DinkPlugin.java
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/SettingsManager.java
src/main/java/dinkplugin/notifiers/DeathNotifier.java
src/main/java/dinkplugin/util/WorldUtils.java
src/test/java/dinkplugin/notifiers/DeathNotifierTest.java

feat(death): allow customization of ignored regions

---

CHANGELOG.md
runelite-plugin.properties
src/main/java/dinkplugin/DinkPlugin.java

chore: update plugin description

---

CHANGELOG.md
README.md
src/main/java/dinkplugin/util/WorldUtils.java

https://oldschool.runescape.wiki/w/Mage_Training_Arena/Creature_Graveyard

fix: treat mage training arena as a safe death

---

CHANGELOG.md
docs/json-examples.md
src/main/java/dinkplugin/notifiers/DeathNotifier.java
src/main/java/dinkplugin/notifiers/data/DeathNotificationData.java
src/main/java/dinkplugin/util/Region.java
src/test/java/dinkplugin/notifiers/DeathNotifierTest.java

feat: include region in death metadata

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/notifiers/LootNotifier.java
src/test/java/dinkplugin/notifiers/LootNotifierTest.java

feat: fire loot notif for pk chests if total value exceeds min

---

gradle/wrapper/gradle-wrapper.properties

https://docs.gradle.org/8.6/release-notes.html#upgrade-instructions

chore: bump gradle to v8.6

---

CHANGELOG.md
docs/json-examples.md
src/main/java/dinkplugin/DinkPlugin.java
src/main/java/dinkplugin/notifiers/ClueNotifier.java
src/main/java/dinkplugin/notifiers/CollectionNotifier.java
src/main/java/dinkplugin/notifiers/data/CollectionNotificationData.java
src/main/java/dinkplugin/notifiers/data/LootNotificationData.java
src/main/java/dinkplugin/util/Drop.java
src/main/java/dinkplugin/util/KillCountService.java
src/test/java/dinkplugin/notifiers/CollectionNotifierTest.java
src/test/java/dinkplugin/notifiers/LootNotifierTest.java

Follow-up from #392; Closes #371

feat: add kill count to collection log notifications

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/notifiers/LootNotifier.java
src/test/java/dinkplugin/notifiers/LootNotifierTest.java

feat: add rarity threshold for loot notifs

---

CHANGELOG.md
README.md
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/notifiers/CollectionNotifier.java
src/test/java/dinkplugin/notifiers/CollectionNotifierTest.java

feat(collection): add completed and total as template vars

---

CHANGELOG.md
build.gradle.kts

Dink v1.9.0 most notably includes monster drop rarity for loot and collection notifications.

Release v1.9.0

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/PetNotifier.java

chore: add quetzin pet handling

---

src/main/java/dinkplugin/notifiers/CollectionNotifier.java

https://oldschool.runescape.wiki/w/Collection_log

chore: update collection log entry count

---

.github/workflows/update-resources.yml

Follow-up to https://github.com/pajlads/DinkPlugin/pull/425#discussion_r1495015187

chore: schedule daily generateResources action

---

docs/json-examples.md

docs: explain multipart body for json consumers

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/PetNotifier.java

they added 2 pets with the varlamore update, unlucky i guess

chore: add smol heredit pet handling

---

src/main/java/dinkplugin/domain/ChatNotificationType.java
src/main/java/dinkplugin/notifiers/CollectionNotifier.java

couple very small changes before #459

perf: use EnumMap for ChatNotificationType

---

CHANGELOG.md
README.md
docs/json-examples.md
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/VersionManager.java
src/main/java/dinkplugin/message/NotificationType.java
src/main/java/dinkplugin/notifiers/LevelNotifier.java
src/main/java/dinkplugin/notifiers/data/XpNotificationData.java
src/test/java/dinkplugin/notifiers/LevelNotifierTest.java

feat: fire notification on xp milestones

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/PlayerKillNotifier.java

fix(pk): avoid double notification for multi-tick special attack

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/KillCountNotifier.java
src/main/java/dinkplugin/notifiers/LootNotifier.java
src/main/java/dinkplugin/util/KillCountService.java
src/test/java/dinkplugin/notifiers/LootNotifierTest.java

fix(loot): distinguish corrupted from normal gauntlet

---

CHANGELOG.md
docs/json-examples.md
src/main/java/dinkplugin/DinkPlugin.java
src/main/java/dinkplugin/notifiers/ChatNotifier.java
src/main/java/dinkplugin/notifiers/data/ChatNotificationData.java
src/test/java/dinkplugin/notifiers/ChatNotifierTest.java

feat: add source to ChatNotificationData

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/DeathNotifier.java
src/main/java/dinkplugin/util/WorldUtils.java

fix: fire death notification for fortis doom modifier

---

docs/json-examples.md

https://togithub.com/pajlads/DinkPlugin/issues/482#issuecomment-2136506185

docs: explain multipart parsing for cloudflare workers

---

gradle/wrapper/gradle-wrapper.properties
gradlew

https://docs.gradle.org/8.8/release-notes.html

chore: update gradle wrapper to v8.8

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/LootNotifier.java
src/main/java/dinkplugin/notifiers/data/RareItemStack.java
src/test/java/dinkplugin/notifiers/LootNotifierTest.java

perf(loot): optimize finding the rarest item

---

CHANGELOG.md
build.gradle.kts

https://github.com/pajlads/DinkPlugin/compare/v1.10.2...41cc135f6d7ed99982bc35d78052d14ff91f8e9b

Release v1.10.3

---

CHANGELOG.md
build.gradle.kts

https://github.com/pajlads/DinkPlugin/compare/v1.10.3...00718785e10837b70c866c2fff3d6f036b384b78

Release v1.10.4

---

src/main/java/dinkplugin/notifiers/CollectionNotifier.java
src/main/java/dinkplugin/util/Utils.java

chore: update number of clog entries for fallback

---

CHANGELOG.md
build.gradle.kts

Dink v1.10.5 fixes some bugs and adds rarity/luck to pet notifications.

Release v1.10.5

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/PlayerKillNotifier.java
src/test/java/dinkplugin/notifiers/PlayerKillNotifierTest.java

thanks jagex https://github.com/runelite/runelite/commit/9d719aa825be9358c2f3a2bbee62891172bf5b4f#diff-7f0abc34d84dafa605f86cc7a2746f5384673841cade18fd88ed0f7db97f1b49

fix(pk): identify correct worn equipment of targets

---

CHANGELOG.md
build.gradle.kts

https://github.com/pajlads/DinkPlugin/compare/v1.10.5...af903859e78b91906cc342fc8f8c39b7be1c0dce

Release v1.10.6

---

CHANGELOG.md
src/main/java/dinkplugin/message/DiscordMessageHandler.java
src/test/java/dinkplugin/notifiers/ChatNotifierTest.java
src/test/java/dinkplugin/notifiers/ClueNotifierTest.java
src/test/java/dinkplugin/notifiers/CollectionNotifierTest.java
src/test/java/dinkplugin/notifiers/CombatTaskNotifierTest.java
src/test/java/dinkplugin/notifiers/DeathNotifierTest.java
src/test/java/dinkplugin/notifiers/DiaryNotifierTest.java
src/test/java/dinkplugin/notifiers/GambleNotifierTest.java
src/test/java/dinkplugin/notifiers/GrandExchangeNotifierTest.java
src/test/java/dinkplugin/notifiers/GroupStorageNotifierTest.java
src/test/java/dinkplugin/notifiers/KillCountNotifierTest.java
src/test/java/dinkplugin/notifiers/LeaguesNotifierTest.java
src/test/java/dinkplugin/notifiers/LevelNotifierTest.java
src/test/java/dinkplugin/notifiers/LootNotifierTest.java
src/test/java/dinkplugin/notifiers/MetaNotifierTest.java
src/test/java/dinkplugin/notifiers/MockedNotifierTest.java
src/test/java/dinkplugin/notifiers/PetNotifierTest.java
src/test/java/dinkplugin/notifiers/PlayerKillNotifierTest.java
src/test/java/dinkplugin/notifiers/QuestNotifierTest.java
src/test/java/dinkplugin/notifiers/SlayerNotifierTest.java
src/test/java/dinkplugin/notifiers/SpeedrunNotifierTest.java
src/test/java/dinkplugin/notifiers/TradeNotifierTest.java

refactor: perform http requests from okhttp thread pool

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/message/DiscordMessageHandler.java
src/main/java/dinkplugin/notifiers/TradeNotifier.java
src/main/java/dinkplugin/util/Utils.java
src/test/java/dinkplugin/notifiers/MockedNotifierTest.java

feat: add setting to include client frame in screenshots

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/PetNotifier.java

https://secure.runescape.com/m=news/araxxor?oldschool=1

feat(pet): add basic support for Nid

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/LootNotifier.java

also changes embed thumbnail to always use max value item instead of rarest

fix(loot): respect denylist when finding max value item

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/LootNotifier.java
src/main/java/dinkplugin/util/KillCountService.java

fix: use LootReceived for Araxxor

---

CHANGELOG.md
build.gradle.kts

https://github.com/pajlads/DinkPlugin/compare/v1.10.6...4a12831c5791059dda272658ffc201ec88af9c5f

Release v1.10.7

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/PetNotifier.java

https://oldschool.runescape.wiki/w/Araxxor#Tertiary (we assume 0% of corpses were destroyed instead of harvested)

chore(pet): update nid drop rate

---

gradle/wrapper/gradle-wrapper.properties

https://docs.gradle.org/8.10.1/release-notes.html

chore: update gradle wrapper to v8.10.1

---

CHANGELOG.md
build.gradle.kts

avoids sending unconfigurable image embeds when rich embed is disabled

Release v1.10.9

---

docs/TESTING.md

Changed in https://github.com/pajlads/DinkPlugin/pull/318

docs: update minimum jdk requirement

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/DeathNotifier.java
src/test/java/dinkplugin/notifiers/DeathNotifierTest.java

fix: accommodate skull icon change

---

CHANGELOG.md
build.gradle.kts

Fixes compilation issue due to new runelite skull icon api

Release v1.10.10

---

gradle/wrapper/gradle-wrapper.properties

https://docs.gradle.org/8.10.2/release-notes.html

chore: update gradle wrapper to v8.10.2

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/message/DiscordMessageHandler.java
src/test/java/dinkplugin/notifiers/MockedNotifierTest.java

feat: allow embed color customization

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPlugin.java
src/main/java/dinkplugin/domain/ExceptionalDeath.java
src/main/java/dinkplugin/notifiers/DeathNotifier.java
src/main/java/dinkplugin/util/WorldUtils.java

Closes #548
https://www.youtube.com/watch?v=UmSkDAStKeE

fix: recognize diary resurrections as safe deaths

---

CHANGELOG.md
build.gradle.kts

https://github.com/pajlads/DinkPlugin/compare/v1.10.10...5ee3ecf85925c94e2898070757ab5fa2ffe2414e

Release v1.10.11

---

src/test/java/dinkplugin/notifiers/MockedNotifierTest.java

avoids sleeping when no post request is being made

chore: speed up test suite when url is absent

---

build.gradle.kts

Enables LWJGL and flatlaf optimizations that are specific to jdk 9+ and 10+
* https://github.com/LWJGL/lwjgl3/blob/3.3.2/modules/lwjgl/core/src/main/java10/org/lwjgl/system/MathUtil.java
* https://github.com/LWJGL/lwjgl3/blob/3.3.2/modules/lwjgl/core/src/main/java10/org/lwjgl/system/MultiReleaseMemCopy.java
* https://github.com/JFormDesigner/FlatLaf/blob/main/flatlaf-core/src/main/java9/com/formdev/flatlaf/ui/StackUtilsImpl.java

chore: enable multi-release for shadow jar

---

CHANGELOG.md
build.gradle.kts

Dink v1.10.12 adds rarity data for notable pickpocket loot
https://github.com/pajlads/DinkPlugin/compare/v1.10.11...a5dcf3dc43c694e94120ee9a0f404ed1c6e5708d

Release v1.10.12

---

src/main/java/dinkplugin/VersionManager.java

No impact on users that already have updated to 1.10.12

chore(VersionManager): add old release notes

---

src/main/java/dinkplugin/notifiers/PetNotifier.java

https://oldschool.runescape.wiki/w/Amoxliatl#Tertiary

chore: add moxi drop rate

---

src/test/java/dinkplugin/RarityCalculator.java

Follow-up to https://github.com/pajlads/DinkPlugin/pull/566#pullrequestreview-2358620181

fix: include rarity of tooth moon key half

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/KillCountNotifier.java
src/test/java/dinkplugin/notifiers/KillCountNotifierTest.java

chore: remove npc image from kill count notifications

---

.github/workflows/lint.yml

swaps to Neri's fork cuz i'm sick of seeing the ⚠️ again

deps(ci): update actionsx-prettier to node 20

---

CHANGELOG.md
build.gradle.kts

https://github.com/pajlads/DinkPlugin/compare/v1.10.12...12022a3fab59f57ab0ede1b1f61fd08994fa31d5

Release v1.10.13

---

CHANGELOG.md
README.md
src/main/java/dinkplugin/message/DiscordMessageHandler.java
src/main/java/dinkplugin/message/NotificationBody.java

https://discord.com/developers/docs/resources/webhook?source=post_page---------------------------#execute-webhook-jsonform-params

feat: allow forum tags to be specified

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/LeaguesNotifier.java

tomorrow is the last day so they might not announce all the relics in time, or the tiers, but here's the early game ones -1

chore: update known relics

---

CHANGELOG.md
build.gradle.kts
docs/MAKE-RELEASE.md
src/main/java/dinkplugin/VersionManager.java

Dink v1.10.14 most notably re-enables the leagues notifier
https://github.com/pajlads/DinkPlugin/compare/v1.10.13...4f07587348aa1dfdc7457f472ea0484ad7f2866f

Release v1.10.14

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/LeaguesNotifier.java

leagues reveal: everything else, unlucky for cache checker

chore: manually confirm relic tiers

---

CHANGELOG.md
src/main/java/dinkplugin/domain/LeagueRelicTier.java
src/main/java/dinkplugin/notifiers/LeaguesNotifier.java

merge if i estimated these thresholds correctly

chore: manually update relic tier points

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPlugin.java
src/main/java/dinkplugin/domain/LeagueTaskDifficulty.java
src/main/java/dinkplugin/notifiers/LeaguesNotifier.java
src/test/java/dinkplugin/notifiers/LeaguesNotifierTest.java

fix: update points for medium leagues tasks and trophy ranks

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/message/NotificationType.java
src/main/java/dinkplugin/notifiers/LeaguesNotifier.java
src/main/java/dinkplugin/notifiers/data/LeaguesMasteryNotificationData.java
src/test/java/dinkplugin/notifiers/LeaguesNotifierTest.java

More intricate metadata can come later once we've found relevant varbits

feat: notify on combat mastery unlock

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/SettingsManager.java
src/main/java/dinkplugin/domain/SeasonalPolicy.java
src/main/java/dinkplugin/message/DiscordMessageHandler.java
src/main/java/dinkplugin/notifiers/BaseNotifier.java
src/test/java/dinkplugin/notifiers/PetNotifierTest.java

feat: allow redirecting all seasonal notifs to leagues url

---

CHANGELOG.md
build.gradle.kts

Leagues fixes: https://github.com/pajlads/DinkPlugin/compare/v1.10.15...172c0f93fbd0577f1840d878594d1dddc40b0407

Release v1.10.16

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/KillCountNotifier.java

fix: update KC regex for echo sol

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/LevelNotifier.java

fix: avoid level notif when hopping from leagues

---

CHANGELOG.md
build.gradle.kts

hopefully be rid of fake all-stats level-up notifications for good this time
490491981edca00a362ec31cbddd2c9d4e05ea17

Release v1.10.18

---

CHANGELOG.md
src/main/java/dinkplugin/SettingsManager.java

https://discord.com/channels/301497432909414422/301497432909414422/1315495518096588841

fix: skip cache when pulling dynamic config

---

CHANGELOG.md
build.gradle.kts

lidl update https://github.com/pajlads/DinkPlugin/compare/765e3a8f20f4d022de586fb3af5798d1446a4269...chore/release-1.10.19

Release v1.10.19

---

CHANGELOG.md
build.gradle.kts

https://github.com/pajlads/DinkPlugin/compare/v1.10.19...7a84fed2deb87359bfd484c98bb4065f1bd92e56

Release v1.10.20

---

.github/workflows/gradle-snapshot.yml
build.gradle.kts

feel free to copy to other projects if happy with this approach

ci: add action to build plugin against snapshot runelite

---

CHANGELOG.md
README.md
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/notifiers/ChatNotifier.java
src/test/java/dinkplugin/notifiers/ChatNotifierTest.java

feat: add `%SENDER%` for chat notifier template

---

CHANGELOG.md
build.gradle.kts

https://github.com/pajlads/DinkPlugin/compare/v1.10.20...chore/release-1.10.21

Release v1.10.21

---

CHANGELOG.md
build.gradle.kts

https://github.com/pajlads/DinkPlugin/compare/v1.10.21...chore/release-1.10.22

Release v1.10.22

---

CHANGELOG.md
README.md
docs/external-plugin-messaging.md
src/main/java/dinkplugin/DinkPluginConfig.java

Addresses https://github.com/runelite/plugin-hub/pull/7561#issuecomment-2693321596

chore: disable external notifier by default

---

CHANGELOG.md
build.gradle.kts

Release v1.11.1

---

CHANGELOG.md
build.gradle.kts

https://github.com/pajlads/DinkPlugin/compare/v1.11.1...chore/release-1.11.2

Release v1.11.2

---

CHANGELOG.md
src/main/java/dinkplugin/message/DiscordMessageHandler.java
src/main/java/dinkplugin/notifiers/ExternalPluginNotifier.java
src/test/java/dinkplugin/notifiers/ExternalPluginNotifierTest.java
src/test/java/dinkplugin/notifiers/MockedNotifierTest.java

fix(external): enrich notification body from client thread

---

CHANGELOG.md
build.gradle.kts

Fixes #675
https://github.com/pajlads/DinkPlugin/compare/v1.11.2...f09c9cc4679de65e37188900beb07620dd6dbd2a

Release v1.11.3

---

docs/external-plugin-messaging.md

Update example code to avoid issues from separate plugins using separate classloaders

docs(external): prefer stdlib to workaround separate classloaders

---

docs/external-plugin-messaging.md
src/test/java/dinkplugin/notifiers/ExternalPluginNotifierTest.java

chore(external): use example code in test cases

---

CHANGELOG.md
build.gradle.kts

https://github.com/pajlads/DinkPlugin/compare/v1.11.3...chore/release-1.11.4

Release v1.11.4

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/PetNotifier.java
src/main/java/dinkplugin/util/KillCountService.java

https://oldschool.runescape.wiki/w/Bran

chore(pet): specify drop rate for bran

---

CHANGELOG.md
src/main/java/dinkplugin/util/KillCountService.java

fix: report correct araxxor kc if loot harvest is delayed

---

CHANGELOG.md
build.gradle.kts

https://github.com/pajlads/DinkPlugin/compare/v1.11.4...chore/release-1.11.5

Release v1.11.5

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPluginConfig.java
src/main/java/dinkplugin/notifiers/BaseNotifier.java
src/main/java/dinkplugin/notifiers/LeaguesNotifier.java
src/main/java/dinkplugin/notifiers/PlayerKillNotifier.java
src/main/java/dinkplugin/notifiers/SpeedrunNotifier.java
src/test/java/dinkplugin/notifiers/MockedNotifierTest.java
src/test/java/dinkplugin/notifiers/PetNotifierTest.java
src/test/java/dinkplugin/notifiers/SpeedrunNotifierTest.java

 feat: allow configuration of denied account types

---

runelite-plugin.properties

chore: change plugin display name

---

CHANGELOG.md
src/main/java/dinkplugin/domain/PlayerLookupService.java

has a few thousand installs https://runelite.net/plugin-hub/show/runeprofile

feat: add RuneProfile player lookup service

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/PetNotifier.java
src/main/java/dinkplugin/util/KillCountService.java

Adds Huberte data to static `Map PET_NAMES_TO_SOURCE` in PetNotifier.

Add Huberte Data to PET_NAMES_TO_SOURCE

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/KillCountNotifier.java
src/test/java/dinkplugin/notifiers/KillCountNotifierTest.java

https://clips.twitch.tv/LightObliviousWalletPhilosoraptor-2BqVgY6GzadUqXQ5

fix: add Yama KC tracking

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/PetNotifier.java

acquisition not yet known, but correct notif message good

feat(pet): add basic support for Yami

---

CHANGELOG.md
build.gradle.kts

This release adds the pet from Hueycoatl to the pet notifier, fixes KC tracking for Yama, and adds support for Yama's pet Yami (unknown drop rate)

Release v1.11.8

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPlugin.java
src/main/java/dinkplugin/notifiers/LootNotifier.java
src/main/java/dinkplugin/util/KillCountService.java

Closes #733 while #732 is still under testing

fix: fire loot notifications for yama

---

CHANGELOG.md
build.gradle.kts

https://github.com/pajlads/DinkPlugin/compare/v1.11.8...chore/release-1.11.9

Release v1.11.9

---

CHANGELOG.md
src/main/java/dinkplugin/DinkPlugin.java
src/main/java/dinkplugin/notifiers/LootNotifier.java
src/main/java/dinkplugin/util/KillCountService.java
src/test/java/dinkplugin/notifiers/LootNotifierTest.java

feat: fire loot notification for pharaoh's sceptre

---

CHANGELOG.md
README.md
src/main/java/dinkplugin/notifiers/ChatNotifier.java

fix(chat): only use newline as pattern delimiter

---

CHANGELOG.md
build.gradle.kts

https://github.com/pajlads/DinkPlugin/compare/v1.11.10...b92478a98cd96a4064c70046f658e5a272749341

Release v1.11.11

---

src/main/java/dinkplugin/notifiers/CollectionNotifier.java
src/test/java/dinkplugin/notifiers/CollectionNotifierTest.java

chore(clog): update fallback total entry count

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/GrandExchangeNotifier.java

Closes #774
forgot to change this threshold after tax percentage changed

fix(ge): correct tax for item values between 50 and 100 gp

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/PetNotifier.java
src/test/java/dinkplugin/notifiers/PetNotifierTest.java

fix: update regex to extract pet from clan message

---

CHANGELOG.md
src/main/java/dinkplugin/util/ConfigUtil.java

fix: import adjusted embed colors

---

CHANGELOG.md
build.gradle.kts

https://github.com/pajlads/DinkPlugin/compare/v1.11.11...chore/release-1.11.12

Release v1.11.12

---

CHANGELOG.md
src/main/java/dinkplugin/notifiers/PetNotifier.java

feat(pet): calculate dom rarity and luck
